"""
WinTools - Software catalog for one-click install.
Sourced from Chris Titus WinUtil + custom additions.
Each entry has:
  - name: display name
  - id: winget package ID
  - category: category name
  - description: short description
  - link: website URL (used for Google Favicons icon loading)
  - icon: local icon path (empty = use favicon/letter fallback)
  - match: substrings to match against installed app names (case-insensitive)
  - foss: whether the app is free and open source
"""

SOFTWARE_CATALOG = [
    # ── Browsers ──────────────────────────────────────────────
    {"name": "Brave", "id": "Brave.Brave", "category": "Browsers", "description": "Privacy-focused browser", "link": "https://www.brave.com", "icon": "", "match": ["brave"], "foss": True},
    {"name": "Chrome", "id": "Google.Chrome", "category": "Browsers", "description": "Fast, secure web browser by Google", "link": "https://www.google.com/chrome/", "icon": "", "match": ["google chrome"], "foss": False},
    {"name": "Chromium", "id": "Hibbiki.Chromium", "category": "Browsers", "description": "Open-source browser, Chrome without Google", "link": "https://github.com/Hibbiki/chromium-win64", "icon": "", "match": ["chromium"], "foss": True},
    {"name": "Edge", "id": "Microsoft.Edge", "category": "Browsers", "description": "Built-in Windows browser", "link": "https://www.microsoft.com/edge", "icon": "", "match": ["microsoft edge"], "foss": False},
    {"name": "Firefox", "id": "Mozilla.Firefox", "category": "Browsers", "description": "Open-source browser by Mozilla", "link": "https://www.mozilla.org/en-US/firefox/new/", "icon": "", "match": ["firefox"], "foss": True},
    {"name": "Firefox ESR", "id": "Mozilla.Firefox.ESR", "category": "Browsers", "description": "Extended Support Release of Firefox", "link": "https://www.mozilla.org/en-US/firefox/enterprise/", "icon": "", "match": ["firefox esr"], "foss": True},
    {"name": "Floorp", "id": "Ablaze.Floorp", "category": "Browsers", "description": "Feature-rich Firefox-based browser", "link": "https://floorp.app/", "icon": "", "match": ["floorp"], "foss": True},
    {"name": "LibreWolf", "id": "LibreWolf.LibreWolf", "category": "Browsers", "description": "Privacy-focused Firefox fork", "link": "https://librewolf-community.gitlab.io/", "icon": "", "match": ["librewolf"], "foss": True},
    {"name": "Mullvad Browser", "id": "MullvadVPN.MullvadBrowser", "category": "Browsers", "description": "Privacy browser by Mullvad", "link": "https://mullvad.net/browser", "icon": "", "match": ["mullvad browser"], "foss": True},
    {"name": "Tor Browser", "id": "TorProject.TorBrowser", "category": "Browsers", "description": "Anonymous web browser", "link": "https://www.torproject.org/", "icon": "", "match": ["tor browser"], "foss": True},
    {"name": "Ungoogled Chromium", "id": "eloston.ungoogled-chromium", "category": "Browsers", "description": "Chromium without Google integration", "link": "https://github.com/Eloston/ungoogled-chromium", "icon": "", "match": ["ungoogled chromium"], "foss": True},
    {"name": "Vivaldi", "id": "Vivaldi.Vivaldi", "category": "Browsers", "description": "Highly customizable browser", "link": "https://vivaldi.com/", "icon": "", "match": ["vivaldi"], "foss": False},
    {"name": "Waterfox", "id": "Waterfox.Waterfox", "category": "Browsers", "description": "Fast Firefox-based browser", "link": "https://www.waterfox.net/", "icon": "", "match": ["waterfox"], "foss": True},
    {"name": "Zen Browser", "id": "Zen-Team.Zen-Browser", "category": "Browsers", "description": "Arc-like Firefox-based browser", "link": "https://zen-browser.app/", "icon": "", "match": ["zen browser"], "foss": True},
    {"name": "Helium", "id": "ImputNet.Helium", "category": "Browsers", "description": "Floating browser window", "link": "https://github.com/imputnet/helium/", "icon": "", "match": ["helium"], "foss": True},

    # ── Communications ──────────────────────────────────────────
    {"name": "Discord", "id": "Discord.Discord", "category": "Communications", "description": "Voice & text chat platform", "link": "https://discord.com/", "icon": "", "match": ["discord"], "foss": False},
    {"name": "Telegram", "id": "Telegram.TelegramDesktop", "category": "Communications", "description": "Cloud messaging app", "link": "https://telegram.org/", "icon": "", "match": ["telegram"], "foss": False},
    {"name": "Signal", "id": "OpenWhisperSystems.Signal", "category": "Communications", "description": "Private messenger", "link": "https://signal.org/", "icon": "", "match": ["signal"], "foss": True},
    {"name": "Slack", "id": "SlackTechnologies.Slack", "category": "Communications", "description": "Team communication", "link": "https://slack.com/", "icon": "", "match": ["slack"], "foss": False},
    {"name": "Teams", "id": "Microsoft.Teams", "category": "Communications", "description": "Microsoft collaboration platform", "link": "https://www.microsoft.com/en-us/microsoft-teams/group-chat-software", "icon": "", "match": ["teams"], "foss": False},
    {"name": "Zoom", "id": "Zoom.Zoom", "category": "Communications", "description": "Video conferencing", "link": "https://zoom.us/", "icon": "", "match": ["zoom"], "foss": False},
    {"name": "Element", "id": "Element.Element", "category": "Communications", "description": "Matrix-based secure chat", "link": "https://element.io/", "icon": "", "match": ["element"], "foss": True},
    {"name": "Thunderbird", "id": "Mozilla.Thunderbird", "category": "Communications", "description": "Email client by Mozilla", "link": "https://www.thunderbird.net/", "icon": "", "match": ["thunderbird"], "foss": True},
    {"name": "Viber", "id": "Rakuten.Viber", "category": "Communications", "description": "Messaging and calling app", "link": "https://www.viber.com/", "icon": "", "match": ["viber"], "foss": False},
    {"name": "TeamSpeak", "id": "TeamSpeakSystems.TeamSpeakClient", "category": "Communications", "description": "Voice chat for gamers", "link": "https://www.teamspeak.com/", "icon": "", "match": ["teamspeak"], "foss": False},
    {"name": "Proton Mail", "id": "Proton.ProtonMail", "category": "Communications", "description": "Encrypted email client", "link": "https://proton.me/mail", "icon": "", "match": ["proton mail"], "foss": True},
    {"name": "Chatterino", "id": "ChatterinoTeam.Chatterino", "category": "Communications", "description": "Twitch chat client", "link": "https://www.chatterino.com/", "icon": "", "match": ["chatterino"], "foss": True},
    {"name": "Vesktop", "id": "Vencord.Vesktop", "category": "Communications", "description": "Vencord Discord client", "link": "https://github.com/Vencord/Vesktop", "icon": "", "match": ["vesktop"], "foss": True},
    {"name": "QTox", "id": "Tox.qTox", "category": "Communications", "description": "Distributed instant messenger", "link": "https://qtox.github.io/", "icon": "", "match": ["qtox"], "foss": True},

    # ── Development ────────────────────────────────────────────
    {"name": "VS Code", "id": "Microsoft.VisualStudioCode", "category": "Development", "description": "Lightweight code editor by Microsoft", "link": "https://code.visualstudio.com/", "icon": "", "match": ["visual studio code"], "foss": True},
    {"name": "VS Codium", "id": "VSCodium.VSCodium", "category": "Development", "description": "Open-source VS Code without telemetry", "link": "https://vscodium.com/", "icon": "", "match": ["vscodium", "codium"], "foss": True},
    {"name": "Cursor", "id": "Anysphere.Cursor", "category": "Development", "description": "AI-powered code editor", "link": "https://cursor.com/", "icon": "", "match": ["cursor"], "foss": False},
    {"name": "Zed", "id": "ZedIndustries.Zed", "category": "Development", "description": "High-performance code editor", "link": "https://zed.dev/", "icon": "", "match": ["zed"], "foss": True},
    {"name": "Orca", "id": "StablyAI.Orca", "category": "Development", "description": "AI-powered code editor by Stably", "link": "https://orca.dev/", "icon": "", "match": ["orca"], "foss": False},
    {"name": "Neovim", "id": "Neovim.Neovim", "category": "Development", "description": "Hyperextensible Vim-based editor", "link": "https://neovim.io/", "icon": "", "match": ["neovim"], "foss": True},
    {"name": "Sublime Text", "id": "SublimeHQ.SublimeText.4", "category": "Development", "description": "Fast text editor", "link": "https://www.sublimetext.com/", "icon": "", "match": ["sublime text"], "foss": False},
    {"name": "Visual Studio 2022", "id": "Microsoft.VisualStudio.2022.Community", "category": "Development", "description": "Full-featured IDE", "link": "https://visualstudio.microsoft.com/", "icon": "", "match": ["visual studio community 2022"], "foss": False},
    {"name": "Git", "id": "Git.Git", "category": "Development", "description": "Version control system", "link": "https://git-scm.com/", "icon": "", "match": ["git (", "git version"], "foss": True},
    {"name": "GitHub Desktop", "id": "GitHub.GitHubDesktop", "category": "Development", "description": "Git GUI client", "link": "https://desktop.github.com/", "icon": "", "match": ["github desktop"], "foss": True},
    {"name": "GitHub CLI", "id": "GitHub.cli", "category": "Development", "description": "GitHub command line tool", "link": "https://cli.github.com/", "icon": "", "match": ["github cli"], "foss": True},
    {"name": "GitHub Copilot", "id": "GitHub.GitHubCopilot", "category": "Development", "description": "AI coding assistant for VS Code", "link": "https://github.com/features/copilot", "icon": "", "match": ["github copilot"], "foss": False},
    {"name": "Python", "id": "Python.Python.3.12", "category": "Development", "description": "Python programming language", "link": "https://www.python.org/", "icon": "", "match": ["python"], "foss": True},
    {"name": "Node.js LTS", "id": "OpenJS.NodeJS.LTS", "category": "Development", "description": "JavaScript runtime (LTS)", "link": "https://nodejs.org/", "icon": "", "match": ["node.js"], "foss": True},
    {"name": "NVM", "id": "CoreyButler.NVMforWindows", "category": "Development", "description": "Node version manager for Windows", "link": "https://github.com/coreybutler/nvm-windows", "icon": "", "match": ["nvm for windows", "nvm"], "foss": True},
    {"name": "Go", "id": "GoLang.Go", "category": "Development", "description": "Go programming language", "link": "https://go.dev/", "icon": "", "match": ["go ", "golang"], "foss": True},
    {"name": "Rust", "id": "Rustlang.Rust.MSVC", "category": "Development", "description": "Rust programming language", "link": "https://www.rust-lang.org/", "icon": "", "match": ["rustup"], "foss": True},
    {"name": "Ruby", "id": "RubyInstallerTeam.Ruby.4.0", "category": "Development", "description": "Ruby programming language", "link": "https://rubyinstaller.org/", "icon": "", "match": ["ruby"], "foss": True},
    {"name": "CMake", "id": "Kitware.CMake", "category": "Development", "description": "Build system generator", "link": "https://cmake.org/", "icon": "", "match": ["cmake"], "foss": True},
    {"name": "Docker Desktop", "id": "Docker.DockerDesktop", "category": "Development", "description": "Container platform", "link": "https://www.docker.com/", "icon": "", "match": ["docker desktop"], "foss": False},
    {"name": "Postman", "id": "Postman.Postman", "category": "Development", "description": "API testing tool", "link": "https://www.postman.com/", "icon": "", "match": ["postman"], "foss": False},
    {"name": "PuTTY", "id": "PuTTY.PuTTY", "category": "Development", "description": "SSH and Telnet client", "link": "https://www.chiark.greenend.org.uk/~sgtatham/putty/", "icon": "", "match": ["putty"], "foss": True},
    {"name": "Windows Terminal", "id": "Microsoft.WindowsTerminal", "category": "Development", "description": "Modern terminal app", "link": "https://aka.ms/terminal", "icon": "", "match": ["windows terminal"], "foss": True},
    {"name": "JetBrains Toolbox", "id": "JetBrains.Toolbox", "category": "Development", "description": "JetBrains IDE manager", "link": "https://www.jetbrains.com/toolbox/", "icon": "", "match": ["jetbrains"], "foss": False},
    {"name": "Android Studio", "id": "Google.AndroidStudio", "category": "Development", "description": "Android development IDE", "link": "https://developer.android.com/studio", "icon": "", "match": ["android studio"], "foss": True},
    {"name": "Unity Hub", "id": "Unity.UnityHub", "category": "Development", "description": "Game engine IDE", "link": "https://unity.com/", "icon": "", "match": ["unity"], "foss": False},
    {"name": "Lazygit", "id": "JesseDuffield.lazygit", "category": "Development", "description": "Terminal UI for Git", "link": "https://github.com/jesseduffield/lazygit/", "icon": "", "match": ["lazygit"], "foss": True},
    {"name": "Oh My Posh", "id": "JanDeDobbeleer.OhMyPosh", "category": "Development", "description": "Custom terminal prompt", "link": "https://ohmyposh.dev/", "icon": "", "match": ["oh my posh"], "foss": True},
    {"name": "pnpm", "id": "pnpm.pnpm", "category": "Development", "description": "Fast, disk-space efficient package manager", "link": "https://pnpm.io/", "icon": "", "match": ["pnpm"], "foss": True},
    {"name": "Yarn", "id": "Yarn.Yarn", "category": "Development", "description": "JavaScript package manager", "link": "https://yarnpkg.com/", "icon": "", "match": ["yarn"], "foss": True},
    {"name": "uv", "id": "astral-sh.uv", "category": "Development", "description": "Fast Python package manager", "link": "https://docs.astral.sh/uv/", "icon": "", "match": ["uv"], "foss": True},
    {"name": "RipGrep", "id": "BurntSushi.ripgrep.MSI", "category": "Development", "description": "Fast text search tool", "link": "https://github.com/BurntSushi/ripgrep", "icon": "", "match": ["ripgrep"], "foss": True},
    {"name": "System Informer", "id": "WinsiderSS.SystemInformer", "category": "Development", "description": "Advanced task manager", "link": "https://systeminformer.com/", "icon": "", "match": ["system informer"], "foss": True},
    {"name": "Claude", "id": "Anthropic.Claude", "category": "Development", "description": "Claude AI desktop app", "link": "https://claude.ai/download", "icon": "", "match": ["claude"], "foss": False},
    {"name": "Claude Code", "id": "Anthropic.ClaudeCode", "category": "Development", "description": "Claude coding CLI agent", "link": "https://code.claude.com/", "icon": "", "match": ["claude code", "anthropic.claudecode"], "foss": True},
    {"name": "ChatGPT Desktop", "id": "OpenAI.ChatGPT", "category": "Development", "description": "ChatGPT desktop app", "link": "https://chat.openai.com/", "icon": "", "match": ["chatgpt", "openai.chatgpt"], "foss": False},
    {"name": "Codex", "id": "OpenAI.Codex", "category": "Development", "description": "OpenAI Codex CLI", "link": "https://developers.openai.com/codex/cli", "icon": "", "match": ["openai.codex", "codex cli"], "foss": True},
    {"name": "gsudo", "id": "gerardog.gsudo", "category": "Development", "description": "Sudo for Windows", "link": "https://github.com/gerardog/gsudo", "icon": "", "match": ["gsudo"], "foss": True},

    # ── Games ──────────────────────────────────────────────────
    {"name": "Steam", "id": "Valve.Steam", "category": "Games", "description": "Game platform by Valve", "link": "https://store.steampowered.com/about/", "icon": "", "match": ["steam"], "foss": False},
    {"name": "Epic Games", "id": "EpicGames.EpicGamesLauncher", "category": "Games", "description": "Epic Games store", "link": "https://www.epicgames.com/store/en-US/", "icon": "", "match": ["epic games"], "foss": False},
    {"name": "EA App", "id": "ElectronicArts.EADesktop", "category": "Games", "description": "EA game launcher", "link": "https://www.ea.com/ea-app", "icon": "", "match": ["ea app", "ea desktop"], "foss": False},
    {"name": "GOG Galaxy", "id": "GOG.Galaxy", "category": "Games", "description": "Multi-platform game launcher", "link": "https://www.gog.com/galaxy", "icon": "", "match": ["gog galaxy"], "foss": False},
    {"name": "GeForce NOW", "id": "Nvidia.GeForceNow", "category": "Games", "description": "Cloud gaming by NVIDIA", "link": "https://www.nvidia.com/en-us/geforce-now/", "icon": "", "match": ["geforce now"], "foss": False},
    {"name": "Heroic Games Launcher", "id": "HeroicGamesLauncher.HeroicGamesLauncher", "category": "Games", "description": "Open-source game launcher", "link": "https://heroicgameslauncher.com/", "icon": "", "match": ["heroic"], "foss": True},
    {"name": "Itch.io", "id": "ItchIo.Itch", "category": "Games", "description": "Indie game marketplace", "link": "https://itch.io/", "icon": "", "match": ["itch.io", "itch"], "foss": True},
    {"name": "Playnite", "id": "Playnite.Playnite", "category": "Games", "description": "Open-source game library manager", "link": "https://playnite.link/", "icon": "", "match": ["playnite"], "foss": True},
    {"name": "Cemu", "id": "Cemu.Cemu", "category": "Games", "description": "Wii U emulator", "link": "https://cemu.info/", "icon": "", "match": ["cemu"], "foss": True},
    {"name": "Prism Launcher", "id": "PrismLauncher.PrismLauncher", "category": "Games", "description": "Minecraft launcher", "link": "https://prismlauncher.org/", "icon": "", "match": ["prism launcher"], "foss": True},
    {"name": "Modrinth App", "id": "Modrinth.ModrinthApp", "category": "Games", "description": "Minecraft mod manager", "link": "https://modrinth.com/app", "icon": "", "match": ["modrinth"], "foss": True},
    {"name": "Ubisoft Connect", "id": "Ubisoft.Connect", "category": "Games", "description": "Ubisoft game launcher", "link": "https://ubisoftconnect.com/", "icon": "", "match": ["ubisoft connect"], "foss": False},
    {"name": "Overwolf", "id": "Overwolf.CurseForge", "category": "Games", "description": "In-game overlay & CurseForge", "link": "https://www.overwolf.com/app/overwolf-curseforge", "icon": "", "match": ["overwolf", "curseforge"], "foss": False},

    # ── Multimedia Tools ────────────────────────────────────────
    {"name": "VLC", "id": "VideoLAN.VLC", "category": "Multimedia Tools", "description": "Media player for all formats", "link": "https://www.videolan.org/vlc/", "icon": "", "match": ["vlc"], "foss": True},
    {"name": "OBS Studio", "id": "OBSProject.OBSStudio", "category": "Multimedia Tools", "description": "Screen recording & streaming", "link": "https://obsproject.com/", "icon": "", "match": ["obs studio"], "foss": True},
    {"name": "Spotify", "id": "Spotify.Spotify", "category": "Multimedia Tools", "description": "Music streaming", "link": "https://www.spotify.com/", "icon": "", "match": ["spotify"], "foss": False},
    {"name": "FFmpeg", "id": "Gyan.FFmpeg", "category": "Multimedia Tools", "description": "Audio/video processing CLI", "link": "https://ffmpeg.org/", "icon": "", "match": ["ffmpeg"], "foss": True},
    {"name": "ShareX", "id": "ShareX.ShareX", "category": "Multimedia Tools", "description": "Screen capture and sharing", "link": "https://getsharex.com/", "icon": "", "match": ["sharex"], "foss": True},
    {"name": "GIMP", "id": "GIMP.GIMP.3", "category": "Multimedia Tools", "description": "Image editor", "link": "https://www.gimp.org/", "icon": "", "match": ["gimp"], "foss": True},
    {"name": "Blender", "id": "BlenderFoundation.Blender", "category": "Multimedia Tools", "description": "3D graphics creation", "link": "https://www.blender.org/", "icon": "", "match": ["blender"], "foss": True},
    {"name": "Audacity", "id": "Audacity.Audacity", "category": "Multimedia Tools", "description": "Audio editor and recorder", "link": "https://www.audacityteam.org/", "icon": "", "match": ["audacity"], "foss": True},
    {"name": "HandBrake", "id": "HandBrake.HandBrake", "category": "Multimedia Tools", "description": "Video transcoder", "link": "https://handbrake.fr/", "icon": "", "match": ["handbrake"], "foss": True},
    {"name": "ImageGlass", "id": "DuongDieuPhap.ImageGlass", "category": "Multimedia Tools", "description": "Lightweight image viewer", "link": "https://imageglass.org/", "icon": "", "match": ["imageglass"], "foss": True},
    {"name": "IrfanView", "id": "IrfanSkiljan.IrfanView", "category": "Multimedia Tools", "description": "Fast image viewer", "link": "https://irfanview.com/", "icon": "", "match": ["irfanview"], "foss": False},
    {"name": "AIMP", "id": "AIMP.AIMP", "category": "Multimedia Tools", "description": "Feature-rich music player", "link": "https://www.aimp.ru/", "icon": "", "match": ["aimp"], "foss": False},
    {"name": "K-Lite Codec Pack", "id": "CodecGuide.K-LiteCodecPack.Standard", "category": "Multimedia Tools", "description": "Codec pack for media playback", "link": "https://www.codecguide.com/", "icon": "", "match": ["k-lite"], "foss": False},
    {"name": "Notepad++", "id": "Notepad++.Notepad++", "category": "Multimedia Tools", "description": "Advanced text editor", "link": "https://notepad-plus-plus.org/", "icon": "", "match": ["notepad++", "notepadplus"], "foss": True},
    {"name": "Obsidian", "id": "Obsidian.Obsidian", "category": "Multimedia Tools", "description": "Markdown note-taking", "link": "https://obsidian.md/", "icon": "", "match": ["obsidian"], "foss": False},
    {"name": "LibreOffice", "id": "TheDocumentFoundation.LibreOffice", "category": "Multimedia Tools", "description": "Free office suite", "link": "https://www.libreoffice.org/", "icon": "", "match": ["libreoffice"], "foss": True},
    {"name": "Calibre", "id": "calibre.calibre", "category": "Multimedia Tools", "description": "E-book manager", "link": "https://calibre-ebook.com/", "icon": "", "match": ["calibre"], "foss": True},
    {"name": "Paint.NET", "id": "dotPDN.PaintDotNet", "category": "Multimedia Tools", "description": "Image and photo editor", "link": "https://www.getpaint.net/", "icon": "", "match": ["paint.net"], "foss": False},
    {"name": "Adobe Acrobat Reader", "id": "Adobe.Acrobat.Reader.64-bit", "category": "Multimedia Tools", "description": "PDF viewer", "link": "https://www.adobe.com/acrobat/pdf-reader.html", "icon": "", "match": ["adobe acrobat", "acrobat reader"], "foss": False},
    {"name": "NAPS2", "id": "Cyanfish.NAPS2", "category": "Multimedia Tools", "description": "Document scanner", "link": "https://www.naps2.com/", "icon": "", "match": ["naps2"], "foss": True},
    {"name": "EarTrumpet", "id": "File-New-Project.EarTrumpet", "category": "Multimedia Tools", "description": "Volume control per app", "link": "https://eartrumpet.app/", "icon": "", "match": ["eartrumpet"], "foss": True},
    {"name": "ImageMagick", "id": "ImageMagick.ImageMagick", "category": "Multimedia Tools", "description": "Image manipulation CLI", "link": "https://imagemagick.org/", "icon": "", "match": ["imagemagick"], "foss": True},

    # ── Microsoft Tools ─────────────────────────────────────────
    {"name": "PowerToys", "id": "Microsoft.PowerToys", "category": "Microsoft Tools", "description": "System utilities for power users", "link": "https://github.com/microsoft/PowerToys", "icon": "", "match": ["powertoys"], "foss": True},
    {"name": "Windows Terminal", "id": "Microsoft.WindowsTerminal", "category": "Microsoft Tools", "description": "Modern terminal app", "link": "https://aka.ms/terminal", "icon": "", "match": ["windows terminal"], "foss": True},
    {"name": "PowerShell", "id": "Microsoft.PowerShell", "category": "Microsoft Tools", "description": "Cross-platform shell", "link": "https://github.com/PowerShell/PowerShell", "icon": "", "match": ["powershell"], "foss": True},
    {"name": ".NET 8 Runtime", "id": "Microsoft.DotNet.DesktopRuntime.8", "category": "Microsoft Tools", "description": ".NET 8 desktop runtime", "link": "https://dotnet.microsoft.com/download/dotnet/8.0", "icon": "", "match": [".net 8", "dotnet 8", ".net runtime 8"], "foss": True},
    {"name": ".NET 9 Runtime", "id": "Microsoft.DotNet.DesktopRuntime.9", "category": "Microsoft Tools", "description": ".NET 9 desktop runtime", "link": "https://dotnet.microsoft.com/download/dotnet/9.0", "icon": "", "match": [".net 9", "dotnet 9", ".net runtime 9"], "foss": True},
    {"name": "VC++ Redist (x64)", "id": "Microsoft.VCRedist.2015+.x64", "category": "Microsoft Tools", "description": "Visual C++ runtime (64-bit)", "link": "https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads", "icon": "", "match": ["visual c++", "vcredist"], "foss": False},
    {"name": "VC++ Redist (x86)", "id": "Microsoft.VCRedist.2015+.x86", "category": "Microsoft Tools", "description": "Visual C++ runtime (32-bit)", "link": "https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads", "icon": "", "match": [], "foss": False},
    {"name": "OneDrive", "id": "Microsoft.OneDrive", "category": "Microsoft Tools", "description": "Microsoft cloud storage", "link": "https://onedrive.live.com/", "icon": "", "match": ["onedrive"], "foss": False},
    {"name": "NuGet", "id": "Microsoft.NuGet", "category": "Microsoft Tools", "description": ".NET package manager", "link": "https://www.nuget.org/", "icon": "", "match": ["nuget"], "foss": True},
    {"name": "Process Explorer", "id": "Microsoft.Sysinternals.ProcessExplorer", "category": "Microsoft Tools", "description": "Advanced process viewer", "link": "https://learn.microsoft.com/sysinternals/downloads/process-explorer", "icon": "", "match": ["process explorer"], "foss": False},
    {"name": "Autoruns", "id": "Microsoft.Sysinternals.Autoruns", "category": "Microsoft Tools", "description": "Startup program manager", "link": "https://learn.microsoft.com/en-us/sysinternals/downloads/autoruns", "icon": "", "match": ["autoruns"], "foss": False},
    {"name": "Process Monitor", "id": "Microsoft.Sysinternals.ProcessMonitor", "category": "Microsoft Tools", "description": "System activity monitor", "link": "https://docs.microsoft.com/en-us/sysinternals/downloads/procmon", "icon": "", "match": ["process monitor", "procmon"], "foss": False},
    {"name": "TCPView", "id": "Microsoft.Sysinternals.TCPView", "category": "Microsoft Tools", "description": "Network connection viewer", "link": "https://docs.microsoft.com/en-us/sysinternals/downloads/tcpview", "icon": "", "match": ["tcpview"], "foss": False},
    {"name": "DISMTools", "id": "CodingWondersSoftware.DISMTools.Stable", "category": "Microsoft Tools", "description": "Windows image management", "link": "https://github.com/CodingWonders/DISMTools", "icon": "", "match": ["dismtools"], "foss": True},

    # ── Pro Tools ────────────────────────────────────────────────
    {"name": "CPU-Z", "id": "CPUID.CPU-Z", "category": "Pro Tools", "description": "System hardware info", "link": "https://www.cpuid.com/softwares/cpu-z.html", "icon": "", "match": ["cpu-z", "cpuid cpu-z"], "foss": False},
    {"name": "HWMonitor", "id": "CPUID.HWMonitor", "category": "Pro Tools", "description": "Hardware monitoring", "link": "https://www.cpuid.com/softwares/hwmonitor.html", "icon": "", "match": ["hwmonitor", "cpuid hwmonitor"], "foss": False},
    {"name": "GPU-Z", "id": "TechPowerUp.GPU-Z", "category": "Pro Tools", "description": "GPU info and monitoring", "link": "https://www.techpowerup.com/gpuz/", "icon": "", "match": ["gpu-z"], "foss": False},
    {"name": "HWiNFO", "id": "REALiX.HWiNFO", "category": "Pro Tools", "description": "Comprehensive system info", "link": "https://www.hwinfo.com/", "icon": "", "match": ["hwinfo"], "foss": False},
    {"name": "CrystalDiskInfo", "id": "CrystalDewWorld.CrystalDiskInfo", "category": "Pro Tools", "description": "Disk health monitor", "link": "https://crystalmark.info/en/software/crystaldiskinfo/", "icon": "", "match": ["crystaldiskinfo"], "foss": False},
    {"name": "CrystalDiskMark", "id": "CrystalDewWorld.CrystalDiskMark", "category": "Pro Tools", "description": "Disk benchmark tool", "link": "https://crystalmark.info/en/software/crystaldiskmark/", "icon": "", "match": ["crystaldiskmark"], "foss": False},
    {"name": "Advanced IP Scanner", "id": "Famatech.AdvancedIPScanner", "category": "Pro Tools", "description": "Network scanner", "link": "https://www.advanced-ip-scanner.com/", "icon": "", "match": ["advanced ip scanner"], "foss": False},
    {"name": "Angry IP Scanner", "id": "angryziber.AngryIPScanner", "category": "Pro Tools", "description": "Open-source network scanner", "link": "https://angryip.org/", "icon": "", "match": ["angry ip scanner"], "foss": True},
    {"name": "Nmap", "id": "Insecure.Nmap", "category": "Pro Tools", "description": "Network port scanner", "link": "https://nmap.org/", "icon": "", "match": ["nmap"], "foss": True},
    {"name": "Wireshark", "id": "WiresharkFoundation.Wireshark", "category": "Pro Tools", "description": "Network protocol analyzer", "link": "https://www.wireshark.org/", "icon": "", "match": ["wireshark"], "foss": True},
    {"name": "Npcap", "id": "Nmap.Npcap", "category": "Pro Tools", "description": "Network packet capture driver for Wireshark & Nmap", "link": "https://npcap.com/", "icon": "", "match": ["npcap"], "foss": True},
    {"name": "WinSCP", "id": "WinSCP.WinSCP", "category": "Pro Tools", "description": "SFTP/SCP client", "link": "https://winscp.net/", "icon": "", "match": ["winscp"], "foss": True},
    {"name": "PuTTY", "id": "PuTTY.PuTTY", "category": "Pro Tools", "description": "SSH and Telnet client", "link": "https://www.chiark.greenend.org.uk/~sgtatham/putty/", "icon": "", "match": ["putty"], "foss": True},
    {"name": "WireGuard", "id": "WireGuard.WireGuard", "category": "Pro Tools", "description": "Fast VPN tunnel", "link": "https://www.wireguard.com/", "icon": "", "match": ["wireguard"], "foss": True},
    {"name": "Mullvad VPN", "id": "MullvadVPN.MullvadVPN", "category": "Pro Tools", "description": "Privacy VPN service", "link": "https://github.com/mullvad/mullvadvpn-app", "icon": "", "match": ["mullvad"], "foss": True},
    {"name": "OpenVPN Connect", "id": "OpenVPNTechnologies.OpenVPNConnect", "category": "Pro Tools", "description": "VPN client", "link": "https://openvpn.net/", "icon": "", "match": ["openvpn"], "foss": False},
    {"name": "Proton VPN", "id": "Proton.ProtonVPN", "category": "Pro Tools", "description": "Secure VPN by Proton", "link": "https://protonvpn.com/", "icon": "", "match": ["proton vpn"], "foss": True},
    {"name": "Cinebench", "id": "Maxon.CinebenchR23", "category": "Pro Tools", "description": "CPU/GPU benchmark", "link": "https://www.maxon.net/en/cinebench", "icon": "", "match": ["cinebench"], "foss": False},
    {"name": "Ventoy", "id": "Ventoy.Ventoy", "category": "Pro Tools", "description": "Bootable USB creator", "link": "https://www.ventoy.net/", "icon": "", "match": ["ventoy"], "foss": True},
    {"name": "Display Driver Uninstaller", "id": "Wagnardsoft.DisplayDriverUninstaller", "category": "Pro Tools", "description": "GPU driver cleanup tool", "link": "https://www.wagnardsoft.com/display-driver-uninstaller-DDU-", "icon": "", "match": ["display driver uninstaller", "ddu"], "foss": False},
    {"name": "Revo Uninstaller", "id": "RevoUninstaller.RevoUninstaller", "category": "Pro Tools", "description": "Advanced uninstaller", "link": "https://www.revouninstaller.com/", "icon": "", "match": ["revo uninstaller"], "foss": False},

    # ── Selfhosted Tools ────────────────────────────────────────
    {"name": "Jellyfin Server", "id": "Jellyfin.Server", "category": "Selfhosted Tools", "description": "Open-source media server", "link": "https://jellyfin.org/", "icon": "", "match": ["jellyfin"], "foss": True},
    {"name": "Jellyfin Player", "id": "Jellyfin.JellyfinMediaPlayer", "category": "Selfhosted Tools", "description": "Jellyfin media player", "link": "https://github.com/jellyfin/jellyfin-media-player", "icon": "", "match": ["jellyfin media player"], "foss": True},
    {"name": "Plex Server", "id": "Plex.PlexMediaServer", "category": "Selfhosted Tools", "description": "Media server", "link": "https://www.plex.tv/your-media/", "icon": "", "match": ["plex media server"], "foss": False},
    {"name": "Plex Desktop", "id": "Plex.Plex", "category": "Selfhosted Tools", "description": "Plex media player", "link": "https://www.plex.tv", "icon": "", "match": ["plex desktop", "plex"], "foss": False},
    {"name": "Kodi", "id": "XBMCFoundation.Kodi", "category": "Selfhosted Tools", "description": "Media center", "link": "https://kodi.tv/", "icon": "", "match": ["kodi"], "foss": True},
    {"name": "LocalSend", "id": "LocalSend.LocalSend", "category": "Selfhosted Tools", "description": "Cross-platform file sharing", "link": "https://localsend.org/", "icon": "", "match": ["localsend"], "foss": True},
    {"name": "Nextcloud Desktop", "id": "Nextcloud.NextcloudDesktop", "category": "Selfhosted Tools", "description": "Self-hosted cloud sync", "link": "https://nextcloud.com/install/#install-clients", "icon": "", "match": ["nextcloud"], "foss": True},
    {"name": "Moonlight", "id": "MoonlightGameStreamingProject.Moonlight", "category": "Selfhosted Tools", "description": "Game streaming client", "link": "https://moonlight-stream.org/", "icon": "", "match": ["moonlight"], "foss": True},
    {"name": "Sunshine", "id": "LizardByte.Sunshine", "category": "Selfhosted Tools", "description": "Game streaming server", "link": "https://github.com/LizardByte/Sunshine", "icon": "", "match": ["sunshine"], "foss": True},
    {"name": "NetBird", "id": "Netbird.Netbird", "category": "Selfhosted Tools", "description": "Mesh VPN", "link": "https://netbird.io/", "icon": "", "match": ["netbird"], "foss": True},

    # ── Security & VPN ─────────────────────────────────────────
    {"name": "AdGuard", "id": "AdGuard.AdGuard", "category": "Security & VPN", "description": "Ad blocker & privacy", "link": "https://adguard.com/", "icon": "", "match": ["adguard"], "foss": False},
    {"name": "cloudflared", "id": "Cloudflare.cloudflared", "category": "Security & VPN", "description": "Cloudflare tunnel client", "link": "https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/", "icon": "", "match": ["cloudflared"], "foss": True},
    {"name": "Gpg4win", "id": "GnuPG.Gpg4win", "category": "Security & VPN", "description": "Email & file encryption", "link": "https://gpg4win.org/", "icon": "", "match": ["gpg4win", "gnu privacy guard"], "foss": True},
    {"name": "Tailscale", "id": "Tailscale.Tailscale", "category": "Security & VPN", "description": "Mesh VPN", "link": "https://tailscale.com/", "icon": "", "match": ["tailscale"], "foss": False},
    {"name": "YubiKey Manager", "id": "Yubico.YubiKeyManager", "category": "Security & VPN", "description": "YubiKey configuration", "link": "https://www.yubico.com/products/yubikey-manager/", "icon": "", "match": ["yubikey manager"], "foss": True},
    {"name": "Bitwarden", "id": "Bitwarden.Bitwarden", "category": "Security & VPN", "description": "Open-source password manager", "link": "https://bitwarden.com/", "icon": "", "match": ["bitwarden"], "foss": True},
    {"name": "1Password", "id": "AgileBits.1Password", "category": "Security & VPN", "description": "Password manager", "link": "https://1password.com/", "icon": "", "match": ["1password"], "foss": False},
    {"name": "KeePassXC", "id": "KeePassXCTeam.KeePassXC", "category": "Security & VPN", "description": "Offline password manager", "link": "https://keepassxc.org/", "icon": "", "match": ["keepassxc"], "foss": True},
    {"name": "Simplewall", "id": "Henry++.simplewall", "category": "Security & VPN", "description": "Firewall tool", "link": "https://github.com/henrypp/simplewall", "icon": "", "match": ["simplewall"], "foss": True},

    # ── Utilities ──────────────────────────────────────────────
    {"name": "7-Zip", "id": "7zip.7zip", "category": "Utilities", "description": "File archiver with high compression", "link": "https://www.7-zip.org/", "icon": "", "match": ["7-zip"], "foss": True},
    {"name": "Everything", "id": "voidtools.Everything", "category": "Utilities", "description": "Instant file search", "link": "https://www.voidtools.com/", "icon": "", "match": ["everything"], "foss": False},
    {"name": "WizTree", "id": "AntibodySoftware.WizTree", "category": "Utilities", "description": "Disk space analyzer", "link": "https://wiztreefree.com/", "icon": "", "match": ["wiztree"], "foss": False},
    {"name": "FileZilla", "id": "FileZilla.FileZilla", "category": "Utilities", "description": "FTP/SFTP client", "link": "https://filezilla-project.org/", "icon": "", "match": ["filezilla"], "foss": True},
    {"name": "AutoHotkey", "id": "AutoHotkey.AutoHotkey", "category": "Utilities", "description": "Scripting for automation", "link": "https://www.autohotkey.com/", "icon": "", "match": ["autohotkey"], "foss": True},
    {"name": "Snipaste", "id": "Snipaste.Snipaste", "category": "Utilities", "description": "Screenshot & pin tool", "link": "https://www.snipaste.com/", "icon": "", "match": ["snipaste"], "foss": False},
    {"name": "AnyDesk", "id": "AnyDesk.AnyDesk", "category": "Utilities", "description": "Remote desktop", "link": "https://anydesk.com/", "icon": "", "match": ["anydesk"], "foss": False},
    {"name": "AnyBurn", "id": "PowerSoftware.AnyBurn", "category": "Utilities", "description": "Lightweight CD/DVD/BD burning software", "link": "https://www.anyburn.com/", "icon": "", "match": ["anyburn"], "foss": False},
    {"name": "WinRAR", "id": "RARLab.WinRAR", "category": "Utilities", "description": "Archive manager", "link": "https://www.win-rar.com/", "icon": "", "match": ["winrar"], "foss": False},
    {"name": "NanaZip", "id": "M2Team.NanaZip", "category": "Utilities", "description": "Modern 7-Zip fork", "link": "https://github.com/M2Team/NanaZip", "icon": "", "match": ["nanazip"], "foss": True},
    {"name": "PeaZip", "id": "Giorgiotani.Peazip", "category": "Utilities", "description": "Cross-platform archiver", "link": "https://peazip.github.io/", "icon": "", "match": ["peazip"], "foss": True},
    {"name": "Rufus", "id": "Rufus.Rufus", "category": "Utilities", "description": "Bootable USB creator", "link": "https://rufus.ie/", "icon": "", "match": ["rufus"], "foss": True},
    {"name": "TreeSize Free", "id": "JAMSoftware.TreeSize.Free", "category": "Utilities", "description": "Disk space manager", "link": "https://www.jam-software.com/treesize_free/", "icon": "", "match": ["treesize"], "foss": False},
    {"name": "Files", "id": "FilesCommunity.Files", "category": "Utilities", "description": "Modern file explorer", "link": "https://github.com/files-community/Files", "icon": "", "match": ["filescommunity", "files app"], "foss": True},
    {"name": "TranslucentTB", "id": "CharlesMilette.TranslucentTB", "category": "Utilities", "description": "Customize taskbar transparency", "link": "https://github.com/TranslucentTB/TranslucentTB", "icon": "", "match": ["translucenttb"], "foss": True},
    {"name": "GlazeWM", "id": "glzr-io.glazewm", "category": "Utilities", "description": "Tiling window manager", "link": "https://github.com/glzr-io/glazewm", "icon": "", "match": ["glazewm"], "foss": True},
    {"name": "Winaero Tweaker", "id": "Winaero.WinaeroTweaker", "category": "Utilities", "description": "Windows tweaking tool", "link": "https://winaero.com/winaero-tweaker/", "icon": "", "match": ["winaero"], "foss": False},
    {"name": "Bulk Crap Uninstaller", "id": "Klocman.BulkCrapUninstaller", "category": "Utilities", "description": "Batch uninstall tool", "link": "https://www.bcuninstaller.com/", "icon": "", "match": ["bulk crap uninstaller", "bcuninstaller"], "foss": True},
    {"name": "UniGetUI", "id": "Devolutions.UniGetUI", "category": "Utilities", "description": "Package manager GUI", "link": "https://devolutions.net/unigetui/", "icon": "", "match": ["unigetui"], "foss": True},
    {"name": "Oracle VirtualBox", "id": "Oracle.VirtualBox", "category": "Utilities", "description": "Virtual machine host", "link": "https://www.virtualbox.org/", "icon": "", "match": ["virtualbox"], "foss": True},
    {"name": "Google Drive", "id": "Google.GoogleDrive", "category": "Utilities", "description": "Google cloud storage", "link": "https://www.google.com/drive/", "icon": "", "match": ["google drive"], "foss": False},
    {"name": "Dropbox", "id": "Dropbox.Dropbox", "category": "Utilities", "description": "Cloud file storage", "link": "https://www.dropbox.com/desktop", "icon": "", "match": ["dropbox"], "foss": False},
    {"name": "iCloud", "id": "AppleInc.iCloud", "category": "Utilities", "description": "Apple cloud sync", "link": "https://www.icloud.com/", "icon": "", "match": ["icloud"], "foss": False},
    {"name": "TeamViewer", "id": "TeamViewer.TeamViewer", "category": "Utilities", "description": "Remote desktop access", "link": "https://www.teamviewer.com/", "icon": "", "match": ["teamviewer"], "foss": False},
    {"name": "Parsec", "id": "Parsec.Parsec", "category": "Utilities", "description": "Remote desktop & gaming", "link": "https://parsec.app/", "icon": "", "match": ["parsec"], "foss": False},
    {"name": "qBittorrent", "id": "qBittorrent.qBittorrent", "category": "Utilities", "description": "BitTorrent client", "link": "https://www.qbittorrent.org/", "icon": "", "match": ["qbittorrent"], "foss": True},
    {"name": "F.lux", "id": "flux.flux", "category": "Utilities", "description": "Blue light filter", "link": "https://justgetflux.com/", "icon": "", "match": ["f.lux", "flux"], "foss": False},
    {"name": "MSI Afterburner", "id": "Guru3D.Afterburner", "category": "Utilities", "description": "GPU overclocking utility", "link": "https://www.msi.com/Landing/afterburner", "icon": "", "match": ["afterburner", "msi afterburner"], "foss": False},
    {"name": "OpenRGB", "id": "OpenRGB.OpenRGB", "category": "Utilities", "description": "RGB lighting control", "link": "https://openrgb.org/", "icon": "", "match": ["openrgb"], "foss": True},
    {"name": "HxD Hex Editor", "id": "MHNexus.HxD", "category": "Utilities", "description": "Hex editor & disk editor", "link": "https://mh-nexus.de/en/hxd/", "icon": "", "match": ["hxd"], "foss": False},
    {"name": "Termius", "id": "Termius.Termius", "category": "Utilities", "description": "SSH client", "link": "https://termius.com/", "icon": "", "match": ["termius"], "foss": False},
    {"name": "Eagle", "id": "Eagle.Eagle", "category": "Utilities", "description": "Design asset manager", "link": "https://eagle.cool/", "icon": "", "match": ["eagle"], "foss": False},
    {"name": "MiniTool Partition Wizard", "id": "MiniTool.PartitionWizard.Free", "category": "Utilities", "description": "Disk partition manager", "link": "https://www.partitionwizard.com/", "icon": "", "match": ["minitool", "partition wizard"], "foss": False},
    {"name": "NVIDIA NVCleanstall", "id": "TechPowerUp.NVCleanstall", "category": "Utilities", "description": "Clean NVIDIA driver installer", "link": "https://www.techpowerup.com/nvcleanstall/", "icon": "", "match": ["nvcleanstall"], "foss": False},
    {"name": "Nilesoft Shell", "id": "Nilesoft.Shell", "category": "Utilities", "description": "Windows context menu editor", "link": "https://nilesoft.org/", "icon": "", "match": ["nilesoft"], "foss": True},
    {"name": "OFGB", "id": "xM4ddy.OFGB", "category": "Utilities", "description": "Remove Windows bloat ads", "link": "https://github.com/xM4ddy/OFGB", "icon": "", "match": ["ofgb"], "foss": True},
    {"name": "Deskflow", "id": "Deskflow.Deskflow", "category": "Utilities", "description": "Share mouse/keyboard across PCs", "link": "https://github.com/deskflow/deskflow", "icon": "", "match": ["deskflow"], "foss": True},

    # ── Runtimes ───────────────────────────────────────────────
    {"name": "JDK 21 (Temurin)", "id": "EclipseAdoptium.Temurin.21.JDK", "category": "Runtimes", "description": "Java 21 Development Kit", "link": "https://aws.amazon.com/corretto", "icon": "", "match": ["java", "jdk", "temurin", "eclipse adoptium"], "foss": True},
    {"name": "Amazon Corretto 21", "id": "Amazon.Corretto.21.JDK", "category": "Runtimes", "description": "Amazon's free JDK 21", "link": "https://aws.amazon.com/corretto", "icon": "", "match": ["corretto 21", "amazon corretto"], "foss": True},
    {"name": "Lua", "id": "rjpcomputing.luaforwindows", "category": "Runtimes", "description": "Lua scripting runtime", "link": "https://github.com/rjpcomputing/luaforwindows", "icon": "", "match": ["lua"], "foss": True},
]

# Category order for display + colors for icon placeholders
CATEGORY_ORDER = [
    "Browsers",
    "Communications",
    "Development",
    "Games",
    "Multimedia Tools",
    "Microsoft Tools",
    "Pro Tools",
    "Selfhosted Tools",
    "Security & VPN",
    "Utilities",
    "Runtimes",
]

# Color palette for category icons (letter placeholder backgrounds)
CATEGORY_COLORS = {
    "Browsers": "#4285F4",
    "Communications": "#7C4DFF",
    "Development": "#AB47BC",
    "Games": "#43A047",
    "Multimedia Tools": "#E53935",
    "Microsoft Tools": "#00897B",
    "Pro Tools": "#607D8B",
    "Selfhosted Tools": "#1E88E5",
    "Security & VPN": "#F57C00",
    "Utilities": "#78909C",
    "Runtimes": "#8D6E63",
}