"""
WinTools - Windows Tweaks Definitions
Registry tweaks and PowerShell commands for customizing Windows settings.
Inspired by Chris Titus WinUtil's tweaks system.

Each tweak defines:
  - id: unique identifier
  - name: display name
  - description: what it does
  - category: Personalization | Privacy & Telemetry | Performance & Power | Security | Hardening
  - registry: list of {path, name, type, value_on, value_off} entries
  - commands: optional {on: [...], off: [...]} PowerShell commands (instead of or in addition to registry)
  - services: optional {on: [{name, startup_type}], off: [{name, startup_type}]} service changes
  - recommended: "on" | "off" — suggested state for a clean setup
  - requires_admin: bool — whether HKLM or elevated commands are needed
  - script_only: bool — if true, can only be applied via exported script, not live
  - risk: "safe" | "moderate" | "risky" — risk level of the tweak
  - warning: optional string — specific cautionary text shown to the user
"""

TWEAK_CATEGORIES = {
    "Personalization": {
        "icon": "🎨",
        "description": "Customize Windows look & feel",
        "tweaks": [
            {
                "id": "dark_mode",
                "name": "Dark Theme",
                "description": "Switch Windows and apps to dark mode",
                "registry": [
                    {
                        "path": r"HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Themes\Personalize",
                        "name": "AppsUseLightTheme",
                        "type": "REG_DWORD",
                        "value_on": 0,
                        "value_off": 1,
                    },
                    {
                        "path": r"HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Themes\Personalize",
                        "name": "SystemUsesLightTheme",
                        "type": "REG_DWORD",
                        "value_on": 0,
                        "value_off": 1,
                    },
                ],
                "recommended": "on",
                "requires_admin": False,
                "risk": "safe",
            },
            {
                "id": "show_file_extensions",
                "name": "Show File Extensions",
                "description": "Always show file extensions in Explorer",
                "registry": [
                    {
                        "path": r"HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced",
                        "name": "HideFileExt",
                        "type": "REG_DWORD",
                        "value_on": 0,
                        "value_off": 1,
                    },
                ],
                "recommended": "on",
                "requires_admin": False,
                "risk": "safe",
            },
            {
                "id": "show_hidden_files",
                "name": "Show Hidden Files",
                "description": "Show hidden files and folders in Explorer",
                "registry": [
                    {
                        "path": r"HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced",
                        "name": "Hidden",
                        "type": "REG_DWORD",
                        "value_on": 1,
                        "value_off": 2,
                    },
                ],
                "recommended": "off",
                "requires_admin": False,
                "risk": "safe",
            },
            {
                "id": "taskbar_centered",
                "name": "Centered Taskbar Icons",
                "description": "Align taskbar icons to center (Windows 11 style)",
                "registry": [
                    {
                        "path": r"HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced",
                        "name": "TaskbarAl",
                        "type": "REG_DWORD",
                        "value_on": 1,
                        "value_off": 0,
                    },
                ],
                "recommended": "on",
                "requires_admin": False,
                "risk": "safe",
            },
            {
                "id": "taskbar_search_icon",
                "name": "Taskbar Search Icon",
                "description": "Show search as a small icon instead of search box on taskbar",
                "registry": [
                    {
                        "path": r"HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Search",
                        "name": "SearchboxTaskbarMode",
                        "type": "REG_DWORD",
                        "value_on": 1,
                        "value_off": 2,
                    },
                ],
                "recommended": "on",
                "requires_admin": False,
                "risk": "safe",
            },
            {
                "id": "taskbar_taskview",
                "name": "Hide Task View Button",
                "description": "Remove Task View button from taskbar",
                "registry": [
                    {
                        "path": r"HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced",
                        "name": "ShowTaskViewButton",
                        "type": "REG_DWORD",
                        "value_on": 0,
                        "value_off": 1,
                    },
                ],
                "recommended": "on",
                "requires_admin": False,
                "risk": "safe",
            },
            {
                "id": "taskbar_widgets",
                "name": "Hide Widgets",
                "description": "Remove Widgets button from taskbar",
                "registry": [
                    {
                        "path": r"HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced",
                        "name": "TaskbarDa",
                        "type": "REG_DWORD",
                        "value_on": 0,
                        "value_off": 1,
                    },
                ],
                "recommended": "on",
                "requires_admin": False,
                "risk": "safe",
            },
            {
                "id": "taskbar_chat",
                "name": "Hide Chat Icon",
                "description": "Remove Chat / Microsoft Teams icon from taskbar",
                "registry": [
                    {
                        "path": r"HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced",
                        "name": "TaskbarMn",
                        "type": "REG_DWORD",
                        "value_on": 0,
                        "value_off": 1,
                    },
                ],
                "recommended": "on",
                "requires_admin": False,
                "risk": "safe",
            },
            {
                "id": "lock_screen_disable",
                "name": "Disable Lock Screen",
                "description": "Skip the lock screen on boot, go straight to login",
                "registry": [
                    {
                        "path": r"HKLM\SOFTWARE\Policies\Microsoft\Windows\Personalization",
                        "name": "NoLockScreen",
                        "type": "REG_DWORD",
                        "value_on": 1,
                        "value_off": 0,
                    },
                ],
                "recommended": "off",
                "requires_admin": True,
                "risk": "safe",
            },
            {
                "id": "verbose_logon",
                "name": "Verbose Logon Messages",
                "description": "Show detailed status messages during startup/shutdown",
                "registry": [
                    {
                        "path": r"HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System",
                        "name": "VerboseStatus",
                        "type": "REG_DWORD",
                        "value_on": 1,
                        "value_off": 0,
                    },
                ],
                "recommended": "off",
                "requires_admin": True,
                "risk": "safe",
            },
            {
                "id": "numlock_startup",
                "name": "NumLock on Startup",
                "description": "Enable NumLock by default on boot",
                "registry": [
                    {
                        "path": r"HKCU\Control Panel\Keyboard",
                        "name": "InitialKeyboardIndicators",
                        "type": "REG_SZ",
                        "value_on": "2",
                        "value_off": "0",
                    },
                ],
                "recommended": "on",
                "requires_admin": False,
                "risk": "safe",
            },
        ],
    },
    "Privacy & Telemetry": {
        "icon": "🔒",
        "description": "Reduce data collection and tracking",
        "tweaks": [
            {
                "id": "disable_online_speech",
                "name": "Disable Online Speech Recognition",
                "description": "Prevent sending voice data to Microsoft for online speech recognition",
                "registry": [
                    {
                        "path": r"HKCU\SOFTWARE\Microsoft\Speech_OneCore\Settings\OnlineSpeechPrivacy",
                        "name": "HasAccepted",
                        "type": "REG_DWORD",
                        "value_on": 0,
                        "value_off": 1,
                    },
                ],
                "recommended": "on",
                "requires_admin": False,
                "risk": "safe",
            },
            {
                "id": "disable_defender_samples",
                "name": "Disable Defender Sample Submission",
                "description": "Prevent Windows Defender from sending file samples to Microsoft",
                "registry": [
                    {
                        "path": r"HKLM\SOFTWARE\Policies\Microsoft\Windows Defender\Spynet",
                        "name": "SubmitSamplesConsent",
                        "type": "REG_DWORD",
                        "value_on": 2,
                        "value_off": 1,
                    },
                ],
                "recommended": "on",
                "requires_admin": True,
                "risk": "safe",
            },
            {
                "id": "disable_wpbt",
                "name": "Disable Windows Platform Binary Table",
                "description": "Prevent OEM boot-time code from executing (security & privacy risk)",
                "registry": [
                    {
                        "path": r"HKLM\SYSTEM\CurrentControlSet\Control\Session Manager",
                        "name": "DisableWpbtExecution",
                        "type": "REG_DWORD",
                        "value_on": 1,
                        "value_off": 0,
                    },
                ],
                "recommended": "on",
                "requires_admin": True,
                "risk": "safe",
            },
        ],
    },
    "Performance & Power": {
        "icon": "⚡",
        "description": "Speed up Windows and reduce resource usage",
        "tweaks": [
            {
                "id": "disable_hibernation",
                "name": "Disable Hibernation",
                "description": "Free up disk space by removing hiberfil.sys (saves several GB on SSD)",
                "registry": [
                    {
                        "path": r"HKLM\SYSTEM\CurrentControlSet\Control\Power",
                        "name": "HibernateEnabled",
                        "type": "REG_DWORD",
                        "value_on": 0,
                        "value_off": 1,
                    },
                ],
                "commands": {
                    "on": ["powercfg /hibernate off"],
                    "off": ["powercfg /hibernate on"],
                },
                "recommended": "on",
                "requires_admin": True,
                "risk": "moderate",
                "warning": "Disables Fast Startup. Laptop users may want hibernation for battery savings.",
            },
            {
                "id": "services_manual",
                "name": "Set Non-Essential Services to Manual",
                "description": "Change unnecessary services from Auto to Manual start (DiagTrack, MapsBroker, StorSvc, SharedAccess)",
                "services": {
                    "on": [
                        {"name": "DiagTrack", "startup_type": "Manual"},
                        {"name": "MapsBroker", "startup_type": "Manual"},
                        {"name": "StorSvc", "startup_type": "Manual"},
                        {"name": "SharedAccess", "startup_type": "Manual"},
                    ],
                    "off": [
                        {"name": "DiagTrack", "startup_type": "Automatic"},
                        {"name": "MapsBroker", "startup_type": "Automatic"},
                        {"name": "StorSvc", "startup_type": "Automatic"},
                        {"name": "SharedAccess", "startup_type": "Automatic"},
                    ],
                },
                "recommended": "on",
                "requires_admin": True,
                "risk": "moderate",
                "warning": "Some services may be needed depending on your usage. MapsBroker affects offline maps.",
            },
            {
                "id": "disable_animations",
                "name": "Disable Animations",
                "description": "Turn off window and taskbar animations for snappier feel",
                "registry": [
                    {
                        "path": r"HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced",
                        "name": "TaskbarAnimations",
                        "type": "REG_DWORD",
                        "value_on": 0,
                        "value_off": 1,
                    },
                    {
                        "path": r"HKCU\Control Panel\Desktop",
                        "name": "MenuShowDelay",
                        "type": "REG_SZ",
                        "value_on": "0",
                        "value_off": "400",
                    },
                    {
                        "path": r"HKCU\Control Panel\Desktop",
                        "name": "WindowArrangementActive",
                        "type": "REG_SZ",
                        "value_on": "0",
                        "value_off": "1",
                    },
                ],
                "recommended": "off",
                "requires_admin": False,
                "risk": "safe",
            },
            {
                "id": "disable_aero_peek",
                "name": "Disable Aero Peek",
                "description": "Disable desktop preview on taskbar hover (show desktop shortcut)",
                "registry": [
                    {
                        "path": r"HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced",
                        "name": "DisablePreviewDesktop",
                        "type": "REG_DWORD",
                        "value_on": 1,
                        "value_off": 0,
                    },
                ],
                "recommended": "on",
                "requires_admin": False,
                "risk": "safe",
            },
            {
                "id": "disable_indexing",
                "name": "Disable Search Indexing",
                "description": "Stop Windows Search indexing to reduce CPU and disk usage",
                "services": {
                    "on": [
                        {"name": "WSearch", "startup_type": "Disabled"},
                    ],
                    "off": [
                        {"name": "WSearch", "startup_type": "Automatic"},
                    ],
                },
                "commands": {
                    "on": ["Stop-Service -Name WSearch -Force -ErrorAction SilentlyContinue"],
                    "off": ["Start-Service -Name WSearch -ErrorAction SilentlyContinue"],
                },
                "recommended": "off",
                "requires_admin": True,
                "risk": "moderate",
                "warning": "File search in Explorer will be significantly slower without indexing.",
            },
            {
                "id": "disable_storage_sense",
                "name": "Disable Storage Sense",
                "description": "Prevent automatic disk cleanup that may delete files unexpectedly",
                "registry": [
                    {
                        "path": r"HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\StorageSense\Parameters\StoragePolicy",
                        "name": "01",
                        "type": "REG_DWORD",
                        "value_on": 0,
                        "value_off": 1,
                    },
                ],
                "recommended": "off",
                "requires_admin": False,
                "risk": "safe",
            },
            {
                "id": "enable_long_paths",
                "name": "Enable Long Paths",
                "description": "Remove the 260-character path length limit (requires admin)",
                "registry": [
                    {
                        "path": r"HKLM\SYSTEM\CurrentControlSet\Control\FileSystem",
                        "name": "LongPathsEnabled",
                        "type": "REG_DWORD",
                        "value_on": 1,
                        "value_off": 0,
                    },
                ],
                "recommended": "on",
                "requires_admin": True,
                "risk": "safe",
            },
            {
                "id": "disable_auto_folder_discovery",
                "name": "Disable Explorer Auto Folder Discovery",
                "description": "Stop Explorer from automatically changing folder type templates",
                "registry": [
                    {
                        "path": r"HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced",
                        "name": "DisallowShaping",
                        "type": "REG_DWORD",
                        "value_on": 1,
                        "value_off": 0,
                    },
                    {
                        "path": r"HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced",
                        "name": "FolderType",
                        "type": "REG_SZ",
                        "value_on": "NotSpecified",
                        "value_off": "",
                    },
                ],
                "recommended": "off",
                "requires_admin": False,
                "risk": "safe",
            },
            {
                "id": "ultimate_performance",
                "name": "Ultimate Performance Power Plan",
                "description": "Enable the hidden Ultimate Performance power plan for max performance",
                "commands": {
                    "on": [
                        "powercfg /duplicatescheme e9a42b02-d5df-448d-aa00-03f14749eb61 2>$null | ForEach-Object { powercfg /setactive $_.ToString().Trim() }",
                    ],
                    "off": [
                        "powercfg /setactive 381b4222-f694-41f0-9685-ff5bb260df2e",
                    ],
                },
                "recommended": "off",
                "requires_admin": True,
                "script_only": True,
                "risk": "risky",
                "warning": "⚠️ NOT FOR LAPTOPS. Increases power consumption, CPU boosting, and heat. Almost no benefit outside sustained rendering workloads.",
            },
            {
                "id": "disable_fullscreen_opt",
                "name": "Disable Fullscreen Optimizations",
                "description": "Improve game performance by disabling FSO for borderless windowed mode",
                "registry": [
                    {
                        "path": r"HKCU\System\GameConfigStore",
                        "name": "GameDVR_DXGIHonorFSEWindowsCompatible",
                        "type": "REG_DWORD",
                        "value_on": 1,
                        "value_off": 0,
                    },
                ],
                "recommended": "off",
                "requires_admin": False,
                "risk": "safe",
            },
        ],
    },
    "Security": {
        "icon": "🛡️",
        "description": "Essential Windows security settings",
        "tweaks": [
            {
                "id": "disable_copilot",
                "name": "Disable Windows AI (Copilot)",
                "description": "Disable Copilot and AI features in Windows",
                "registry": [
                    {
                        "path": r"HKCU\SOFTWARE\Policies\Microsoft\Windows\WindowsAI",
                        "name": "DisableAIDataAnalysis",
                        "type": "REG_DWORD",
                        "value_on": 1,
                        "value_off": 0,
                    },
                ],
                "commands": {
                    "on": [
                        "Get-AppxPackage -Name 'Microsoft.Windows.Ai.Copilot.Provider' -ErrorAction SilentlyContinue | Remove-AppxPackage -AllUsers -ErrorAction SilentlyContinue",
                    ],
                    "off": [],
                },
                "recommended": "on",
                "requires_admin": True,
                "risk": "safe",
            },
            {
                "id": "set_ntp",
                "name": "Set NTP Time Server",
                "description": "Configure Windows to sync time from pool.ntp.org for accurate time",
                "commands": {
                    "on": [
                        "w32tm /config /manualpeerlist:pool.ntp.org /syncfromflags:manual /update",
                        "w32tm /resync",
                    ],
                    "off": [
                        "w32tm /config /syncfromflags:domhier /update",
                        "w32tm /resync",
                    ],
                },
                "recommended": "on",
                "requires_admin": True,
                "risk": "safe",
            },
            {
                "id": "enable_dns_over_https",
                "name": "Enable DNS-over-HTTPS",
                "description": "Encrypt DNS queries for privacy (requires supported DNS provider)",
                "registry": [
                    {
                        "path": r"HKLM\SOFTWARE\Policies\Microsoft\Windows NT\DNSClient",
                        "name": "EnableAutoDoh",
                        "type": "REG_DWORD",
                        "value_on": 2,
                        "value_off": 0,
                    },
                ],
                "recommended": "off",
                "requires_admin": True,
                "risk": "moderate",
                "warning": "May cause DNS resolution issues with some ISPs or networks.",
            },
            {
                "id": "disable_razer_auto",
                "name": "Block Razer Software Auto-Install",
                "description": "Prevent Razer software from auto-installing when plugging in Razer devices",
                "registry": [
                    {
                        "path": r"HKLM\SOFTWARE\Policies\Microsoft\Windows\DeviceInstall\Settings",
                        "name": "AllowDeviceInstallations",
                        "type": "REG_DWORD",
                        "value_on": 0,
                        "value_off": 1,
                    },
                ],
                "recommended": "off",
                "requires_admin": True,
                "risk": "moderate",
                "warning": "This blocks ALL automatic device driver installations, not just Razer.",
            },
            {
                "id": "enable_bitlocker",
                "name": "Enable BitLocker",
                "description": "Encrypt drives with BitLocker (requires TPM, runs as script only)",
                "commands": {
                    "on": [
                        "Enable-BitLocker -MountPoint 'C:' -EncryptionMethod XtsAes256 -UsedSpaceOnly -SkipHardwareTest",
                    ],
                    "off": [
                        "Disable-BitLocker -MountPoint 'C:'",
                    ],
                },
                "recommended": "off",
                "requires_admin": True,
                "script_only": True,
                "risk": "risky",
                "warning": "Encrypts your entire drive. Do NOT enable without a backup of your recovery key.",
            },
            {
                "id": "disable_rdp_unsigned_warnings",
                "name": "Disable RDP Unsigned File Warnings",
                "description": "Remove warnings when opening unsigned RDP files",
                "registry": [
                    {
                        "path": r"HKLM\SOFTWARE\Policies\Microsoft\Windows\Safer\CodeIdentifiers",
                        "name": "AuthenticodeEnabled",
                        "type": "REG_DWORD",
                        "value_on": 0,
                        "value_off": 1,
                    },
                ],
                "recommended": "off",
                "requires_admin": True,
                "risk": "moderate",
                "warning": "Disables authenticode checking, which could allow unsigned code to run without warning.",
            },
        ],
    },
    "Hardening": {
        "icon": "⚔️",
        "description": "Advanced security hardening from Windows Hardening Script",
        "tweaks": [
            # ── SAFE ──────────────────────────────────────────────────
            {
                "id": "enable_smart_screen",
                "name": "Enable SmartScreen",
                "description": "Keep SmartScreen filter on for phishing/malware protection",
                "registry": [
                    {
                        "path": r"HKLM\SOFTWARE\Policies\Microsoft\Windows\System",
                        "name": "EnableSmartScreen",
                        "type": "REG_DWORD",
                        "value_on": 1,
                        "value_off": 0,
                    },
                ],
                "recommended": "on",
                "requires_admin": True,
                "risk": "safe",
            },
            {
                "id": "disable_wpad",
                "name": "Disable WPAD",
                "description": "Prevent WPAD proxy auto-discovery (spoofing risk)",
                "registry": [
                    {
                        "path": r"HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings\Wpad",
                        "name": "WpadOverride",
                        "type": "REG_DWORD",
                        "value_on": 1,
                        "value_off": 0,
                    },
                ],
                "recommended": "on",
                "requires_admin": True,
                "risk": "safe",
            },
            {
                "id": "disable_llmnr",
                "name": "Disable LLMNR",
                "description": "Prevent Link-Local Multicast Name Resolution spoofing",
                "registry": [
                    {
                        "path": r"HKLM\SOFTWARE\Policies\Microsoft\Windows NT\DNSClient",
                        "name": "EnableLLMNR",
                        "type": "REG_DWORD",
                        "value_on": 0,
                        "value_off": 1,
                    },
                ],
                "recommended": "on",
                "requires_admin": True,
                "risk": "safe",
            },
            {
                "id": "disable_nbt_ns",
                "name": "Disable NetBIOS Name Service",
                "description": "Prevent NetBIOS name service spoofing attacks",
                "registry": [
                    {
                        "path": r"HKLM\SYSTEM\CurrentControlSet\Services\Netbt\Parameters",
                        "name": "NoNameReleaseOnDemand",
                        "type": "REG_DWORD",
                        "value_on": 1,
                        "value_off": 0,
                    },
                ],
                "recommended": "on",
                "requires_admin": True,
                "risk": "safe",
            },
            {
                "id": "disable_winrm_unencrypted",
                "name": "Require Encrypted WinRM",
                "description": "Block unencrypted WinRM traffic",
                "registry": [
                    {
                        "path": r"HKLM\SOFTWARE\Policies\Microsoft\Windows\WinRM\Service",
                        "name": "AllowUnencryptedTraffic",
                        "type": "REG_DWORD",
                        "value_on": 0,
                        "value_off": 1,
                    },
                    {
                        "path": r"HKLM\SOFTWARE\Policies\Microsoft\Windows\WinRM\Client",
                        "name": "AllowDigest",
                        "type": "REG_DWORD",
                        "value_on": 0,
                        "value_off": 1,
                    },
                ],
                "recommended": "on",
                "requires_admin": True,
                "risk": "safe",
            },
            {
                "id": "block_dangerous_extensions",
                "name": "Block Dangerous File Associations",
                "description": "Associate .bat, .cmd, .vbs, .ps1, .js, .hta, .iso, .reg, etc. with Notepad instead of executing",
                "commands": {
                    "on": [
                        'cmd /c "assoc .bat=txtfile & assoc .cmd=txtfile & assoc .vbs=txtfile & assoc .vbe=txtfile & assoc .js=txtfile & assoc .jse=txtfile & assoc .wsh=txtfile & assoc .wsc=txtfile & assoc .wsf=txtfile & assoc .ws=txtfile & assoc .chm=txtfile & assoc .hta=txtfile & assoc .scr=txtfile & assoc .ps1=txtfile & assoc .iso=txtfile & assoc .reg=txtfile"',
                    ],
                    "off": [],
                },
                "recommended": "on",
                "requires_admin": True,
                "risk": "safe",
            },
            {
                "id": "disable_auto_run_hardening",
                "name": "Disable AutoRun (Enhanced)",
                "description": "Disable AutoRun/AutoPlay on all drives (HKLM + HKCU + NoDriveTypeAutoRun)",
                "registry": [
                    {
                        "path": r"HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer",
                        "name": "NoDriveTypeAutoRun",
                        "type": "REG_DWORD",
                        "value_on": 255,
                        "value_off": 145,
                    },
                    {
                        "path": r"HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer",
                        "name": "NoAutorun",
                        "type": "REG_DWORD",
                        "value_on": 1,
                        "value_off": 0,
                    },
                    {
                        "path": r"HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer",
                        "name": "NoDriveTypeAutoRun",
                        "type": "REG_DWORD",
                        "value_on": 255,
                        "value_off": 145,
                    },
                    {
                        "path": r"HKLM\SOFTWARE\Policies\Microsoft\Windows\Explorer",
                        "name": "NoAutoplayfornonVolume",
                        "type": "REG_DWORD",
                        "value_on": 1,
                        "value_off": 0,
                    },
                ],
                "recommended": "on",
                "requires_admin": True,
                "risk": "safe",
            },
            {
                "id": "enable_uac",
                "name": "Keep UAC Enabled",
                "description": "Ensure UAC is enabled with secure consent prompt (ConsentPromptBehaviorAdmin = 2)",
                "registry": [
                    {
                        "path": r"HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System",
                        "name": "EnableLUA",
                        "type": "REG_DWORD",
                        "value_on": 1,
                        "value_off": 1,
                    },
                    {
                        "path": r"HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System",
                        "name": "ConsentPromptBehaviorAdmin",
                        "type": "REG_DWORD",
                        "value_on": 2,
                        "value_off": 5,
                    },
                    {
                        "path": r"HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System",
                        "name": "EnableVirtualization",
                        "type": "REG_DWORD",
                        "value_on": 1,
                        "value_off": 1,
                    },
                ],
                "recommended": "on",
                "requires_admin": True,
                "risk": "safe",
            },
            {
                "id": "disable_null_sessions",
                "name": "Restrict Null Sessions",
                "description": "Restrict anonymous SAM/LSA access and null session enumeration",
                "registry": [
                    {
                        "path": r"HKLM\SYSTEM\CurrentControlSet\Control\Lsa",
                        "name": "RestrictAnonymousSAM",
                        "type": "REG_DWORD",
                        "value_on": 1,
                        "value_off": 0,
                    },
                    {
                        "path": r"HKLM\SYSTEM\CurrentControlSet\Control\Lsa",
                        "name": "RestrictAnonymous",
                        "type": "REG_DWORD",
                        "value_on": 1,
                        "value_off": 0,
                    },
                    {
                        "path": r"HKLM\SYSTEM\CurrentControlSet\Control\Lsa",
                        "name": "EveryoneIncludesAnonymous",
                        "type": "REG_DWORD",
                        "value_on": 0,
                        "value_off": 1,
                    },
                    {
                        "path": r"HKLM\SYSTEM\CurrentControlSet\Control\LSA\MSV1_0",
                        "name": "allownullsessionfallback",
                        "type": "REG_DWORD",
                        "value_on": 0,
                        "value_off": 1,
                    },
                ],
                "recommended": "on",
                "requires_admin": True,
                "risk": "safe",
            },
            {
                "id": "disable_wdigest",
                "name": "Disable WDigest Credential Storage",
                "description": "Prevent WDigest from storing plain-text passwords in LSASS",
                "registry": [
                    {
                        "path": r"HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\WDigest",
                        "name": "UseLogonCredential",
                        "type": "REG_DWORD",
                        "value_on": 0,
                        "value_off": 1,
                    },
                    {
                        "path": r"HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\WDigest",
                        "name": "Negotiate",
                        "type": "REG_DWORD",
                        "value_on": 0,
                        "value_off": 1,
                    },
                ],
                "recommended": "on",
                "requires_admin": True,
                "risk": "safe",
            },
            {
                "id": "enable_credential_guard",
                "name": "Enable Credential Guard Protections",
                "description": "LSASS RunAsPPL, DisableRestrictedAdmin, CredSSP restricted, LimitBlankPasswordUse",
                "registry": [
                    {
                        "path": r"HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\LSASS.exe",
                        "name": "AuditLevel",
                        "type": "REG_DWORD",
                        "value_on": 8,
                        "value_off": 0,
                    },
                    {
                        "path": r"HKLM\SYSTEM\CurrentControlSet\Control\Lsa",
                        "name": "RunAsPPL",
                        "type": "REG_DWORD",
                        "value_on": 1,
                        "value_off": 0,
                    },
                    {
                        "path": r"HKLM\SYSTEM\CurrentControlSet\Control\Lsa",
                        "name": "DisableRestrictedAdmin",
                        "type": "REG_DWORD",
                        "value_on": 0,
                        "value_off": 1,
                    },
                    {
                        "path": r"HKLM\SYSTEM\CurrentControlSet\Control\Lsa",
                        "name": "DisableRestrictedAdminOutboundCreds",
                        "type": "REG_DWORD",
                        "value_on": 1,
                        "value_off": 0,
                    },
                    {
                        "path": r"HKLM\SOFTWARE\Policies\Microsoft\Windows\CredentialsDelegation",
                        "name": "AllowProtectedCreds",
                        "type": "REG_DWORD",
                        "value_on": 1,
                        "value_off": 0,
                    },
                    {
                        "path": r"HKLM\SYSTEM\CurrentControlSet\Control\Lsa",
                        "name": "LimitBlankPasswordUse",
                        "type": "REG_DWORD",
                        "value_on": 1,
                        "value_off": 0,
                    },
                ],
                "recommended": "on",
                "requires_admin": True,
                "risk": "safe",
            },
            {
                "id": "disable_ipv6_source_routing",
                "name": "Disable IP Source Routing",
                "description": "Block source-routed packets for both IPv4 and IPv6",
                "registry": [
                    {
                        "path": r"HKLM\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters",
                        "name": "DisableIPSourceRouting",
                        "type": "REG_DWORD",
                        "value_on": 2,
                        "value_off": 0,
                    },
                    {
                        "path": r"HKLM\SYSTEM\CurrentControlSet\Services\Tcpip6\Parameters",
                        "name": "DisableIPSourceRouting",
                        "type": "REG_DWORD",
                        "value_on": 2,
                        "value_off": 0,
                    },
                ],
                "recommended": "on",
                "requires_admin": True,
                "risk": "safe",
            },
            {
                "id": "disable_icmp_redirect",
                "name": "Disable ICMP Redirects",
                "description": "Block ICMP redirects that can modify routing tables",
                "registry": [
                    {
                        "path": r"HKLM\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters",
                        "name": "EnableICMPRedirect",
                        "type": "REG_DWORD",
                        "value_on": 0,
                        "value_off": 1,
                    },
                ],
                "recommended": "on",
                "requires_admin": True,
                "risk": "safe",
            },
            {
                "id": "enable_smb_signing",
                "name": "Require SMB Signing",
                "description": "Enable SMB security signatures for LanmanServer and LanmanWorkstation",
                "registry": [
                    {
                        "path": r"HKLM\System\CurrentControlSet\Services\LanmanWorkStation\Parameters",
                        "name": "RequireSecuritySignature",
                        "type": "REG_DWORD",
                        "value_on": 1,
                        "value_off": 0,
                    },
                    {
                        "path": r"HKLM\System\CurrentControlSet\Services\LanmanWorkStation\Parameters",
                        "name": "EnableSecuritySignature",
                        "type": "REG_DWORD",
                        "value_on": 1,
                        "value_off": 0,
                    },
                    {
                        "path": r"HKLM\System\CurrentControlSet\Services\LanmanServer\Parameters",
                        "name": "RequireSecuritySignature",
                        "type": "REG_DWORD",
                        "value_on": 1,
                        "value_off": 0,
                    },
                    {
                        "path": r"HKLM\System\CurrentControlSet\Services\LanmanServer\Parameters",
                        "name": "EnableSecuritySignature",
                        "type": "REG_DWORD",
                        "value_on": 1,
                        "value_off": 0,
                    },
                ],
                "recommended": "on",
                "requires_admin": True,
                "risk": "safe",
            },
            {
                "id": "disable_smb1_hardening",
                "name": "Disable SMBv1 (Enhanced)",
                "description": "Disable SMB1 protocol + disable MRXSMB10 driver (comprehensive SMBv1 removal)",
                "registry": [
                    {
                        "path": r"HKLM\SYSTEM\CurrentControlSet\Services\LanmanServer\Parameters",
                        "name": "SMB1",
                        "type": "REG_DWORD",
                        "value_on": 0,
                        "value_off": 1,
                    },
                    {
                        "path": r"HKLM\SYSTEM\CurrentControlSet\Services\mrxsmb10",
                        "name": "Start",
                        "type": "REG_DWORD",
                        "value_on": 4,
                        "value_off": 3,
                    },
                ],
                "commands": {
                    "on": ["Disable-WindowsOptionalFeature -Online -FeatureName smb1protocol -ErrorAction SilentlyContinue"],
                    "off": [],
                },
                "recommended": "on",
                "requires_admin": True,
                "risk": "safe",
            },
            {
                "id": "disable_powershell_v2",
                "name": "Disable PowerShell v2",
                "description": "Remove PowerShell v2 engine (legacy attack surface)",
                "commands": {
                    "on": [
                        "Disable-WindowsOptionalFeature -Online -FeatureName MicrosoftWindowsPowerShellV2 -ErrorAction SilentlyContinue",
                        "Disable-WindowsOptionalFeature -Online -FeatureName MicrosoftWindowsPowerShellV2Root -ErrorAction SilentlyContinue",
                    ],
                    "off": [],
                },
                "recommended": "on",
                "requires_admin": True,
                "risk": "safe",
            },
            {
                "id": "enable_asr_rules",
                "name": "Enable Attack Surface Reduction Rules",
                "description": "Windows Defender ASR rules for Office, scripts, credential theft, and email threats",
                "commands": {
                    "on": [
                        "Set-MpPreference -AttackSurfaceReductionRules_Ids D1E49AAC-8F56-4280-B9BA-993A6D -AttackSurfaceReductionRules_Actions Enabled -ErrorAction SilentlyContinue",
                        "Add-MpPreference -AttackSurfaceReductionRules_Ids D4F940AB-401B-4EFC-AADC-AD5F3C50688A -AttackSurfaceReductionRules_Actions Enabled -ErrorAction SilentlyContinue",
                        "Add-MpPreference -AttackSurfaceReductionRules_Ids 75668C1F-73B5-4CF0-BB93-3ECF5CB7CC84 -AttackSurfaceReductionRules_Actions Enabled -ErrorAction SilentlyContinue",
                        "Add-MpPreference -AttackSurfaceReductionRules_Ids 92E97FA1-2EDF-4476-BDD6-9DD0B4DDDC7B -AttackSurfaceReductionRules_Actions Enabled -ErrorAction SilentlyContinue",
                        "Add-MpPreference -AttackSurfaceReductionRules_Ids 3B576869-A4EC-4529-8536-B80A7769E899 -AttackSurfaceReductionRules_Actions Enabled -ErrorAction SilentlyContinue",
                        "Add-MpPreference -AttackSurfaceReductionRules_Ids 5BEB7EFE-FD9A-4556-801D-275E5FFC04CC -AttackSurfaceReductionRules_Actions Enabled -ErrorAction SilentlyContinue",
                        "Add-MpPreference -AttackSurfaceReductionRules_Ids BE9BA2D9-53EA-4CDC-84E5-9B1EEEE46550 -AttackSurfaceReductionRules_Actions Enabled -ErrorAction SilentlyContinue",
                        "Add-MpPreference -AttackSurfaceReductionRules_Ids D3E037E1-3EB8-44C8-A917-57927947596D -AttackSurfaceReductionRules_Actions Enabled -ErrorAction SilentlyContinue",
                        "Add-MpPreference -AttackSurfaceReductionRules_Ids 01443614-cd74-433a-b99e-2ecdc07bfc25 -AttackSurfaceReductionRules_Actions Enabled -ErrorAction SilentlyContinue",
                        "Add-MpPreference -AttackSurfaceReductionRules_Ids C1DB55AB-C21A-4637-BB3F-A12568109D35 -AttackSurfaceReductionRules_Actions Enabled -ErrorAction SilentlyContinue",
                        "Add-MpPreference -AttackSurfaceReductionRules_Ids 9E6C4E1F-7D60-472F-BA1A-A39EF669E4B2 -AttackSurfaceReductionRules_Actions Enabled -ErrorAction SilentlyContinue",
                        "Add-MpPreference -AttackSurfaceReductionRules_Ids B2B3F03D-6A65-4F7B-A9C7-1C7EF74A9BA4 -AttackSurfaceReductionRules_Actions Enabled -ErrorAction SilentlyContinue",
                    ],
                    "off": [],
                },
                "recommended": "on",
                "requires_admin": True,
                "risk": "safe",
            },
            {
                "id": "enable_controlled_folder_access",
                "name": "Enable Controlled Folder Access",
                "description": "Prevent unauthorized apps from modifying protected folders (ransomware protection)",
                "commands": {
                    "on": ["Set-MpPreference -EnableControlledFolderAccess Enabled -ErrorAction SilentlyContinue"],
                    "off": ["Set-MpPreference -EnableControlledFolderAccess Disabled -ErrorAction SilentlyContinue"],
                },
                "recommended": "on",
                "requires_admin": True,
                "risk": "safe",
            },
            {
                "id": "enable_network_protection",
                "name": "Enable Network Protection",
                "description": "Windows Defender network protection layer",
                "commands": {
                    "on": ["Set-MpPreference -EnableNetworkProtection Enabled -ErrorAction SilentlyContinue"],
                    "off": ["Set-MpPreference -EnableNetworkProtection Disabled -ErrorAction SilentlyContinue"],
                },
                "recommended": "on",
                "requires_admin": True,
                "risk": "safe",
            },
            {
                "id": "lock_screen_camera",
                "name": "Block Lock Screen Camera",
                "description": "Prevent camera access from lock screen",
                "registry": [
                    {
                        "path": r"HKLM\SOFTWARE\Policies\Microsoft\Windows\Personalization",
                        "name": "NoLockScreenCamera",
                        "type": "REG_DWORD",
                        "value_on": 1,
                        "value_off": 0,
                    },
                ],
                "recommended": "on",
                "requires_admin": True,
                "risk": "safe",
            },
            {
                "id": "disable_voice_activation_lock",
                "name": "Disable Voice Activation on Lock Screen",
                "description": "Prevent apps from activating with voice above lock screen",
                "registry": [
                    {
                        "path": r"HKLM\SOFTWARE\Policies\Microsoft\Windows\AppPrivacy",
                        "name": "LetAppsActivateWithVoiceAboveLock",
                        "type": "REG_DWORD",
                        "value_on": 2,
                        "value_off": 0,
                    },
                    {
                        "path": r"HKLM\SOFTWARE\Policies\Microsoft\Windows\AppPrivacy",
                        "name": "LetAppsActivateWithVoice",
                        "type": "REG_DWORD",
                        "value_on": 2,
                        "value_off": 0,
                    },
                ],
                "recommended": "on",
                "requires_admin": True,
                "risk": "safe",
            },
            {
                "id": "enable_auditing",
                "name": "Enable Security Auditing",
                "description": "Enable process creation auditing, logon/off events, removable storage monitoring",
                "registry": [
                    {
                        "path": r"HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System\Audit",
                        "name": "ProcessCreationIncludeCmdLine_Enabled",
                        "type": "REG_DWORD",
                        "value_on": 1,
                        "value_off": 0,
                    },
                    {
                        "path": r"HKLM\SYSTEM\CurrentControlSet\Control\Lsa",
                        "name": "SCENoApplyLegacyAuditPolicy",
                        "type": "REG_DWORD",
                        "value_on": 1,
                        "value_off": 0,
                    },
                    {
                        "path": r"HKLM\SOFTWARE\Policies\Microsoft\Windows\PowerShell\ModuleLogging",
                        "name": "EnableModuleLogging",
                        "type": "REG_DWORD",
                        "value_on": 1,
                        "value_off": 0,
                    },
                    {
                        "path": r"HKLM\SOFTWARE\Policies\Microsoft\Windows\PowerShell\ScriptBlockLogging",
                        "name": "EnableScriptBlockLogging",
                        "type": "REG_DWORD",
                        "value_on": 1,
                        "value_off": 0,
                    },
                ],
                "commands": {
                    "on": [
                        "Auditpol /set /subcategory:'Security Group Management' /success:enable /failure:enable",
                        "Auditpol /set /subcategory:'Process Creation' /success:enable /failure:enable",
                        "Auditpol /set /subcategory:'Logon' /success:enable /failure:enable",
                        "Auditpol /set /subcategory:'Logoff' /success:enable /failure:disable",
                        "Auditpol /set /subcategory:'Removable Storage' /success:enable /failure:enable",
                        "Auditpol /set /subcategory:'Security State Change' /success:enable /failure:enable",
                        "Auditpol /set /subcategory:'Security System Extension' /success:enable /failure:enable",
                        "Auditpol /set /subcategory:'System Integrity' /success:enable /failure:enable",
                    ],
                    "off": [],
                },
                "recommended": "on",
                "requires_admin": True,
                "risk": "safe",
            },
            {
                "id": "disable_smartscreen_override",
                "name": "Block SmartScreen Override",
                "description": "Prevent users from bypassing SmartScreen warnings",
                "registry": [
                    {
                        "path": r"HKLM\SOFTWARE\Policies\Microsoft\Windows\System",
                        "name": "ShellSmartScreenLevel",
                        "type": "REG_SZ",
                        "value_on": "Block",
                        "value_off": "Warn",
                    },
                ],
                "recommended": "on",
                "requires_admin": True,
                "risk": "safe",
            },
            # ── MODERATE ──────────────────────────────────────────────
            {
                "id": "disable_netbios_tcp",
                "name": "Disable NetBIOS over TCP/IP",
                "description": "Set NetBIOS over TCP/IP to disabled on all adapters",
                "commands": {
                    "on": [
                        "wmic /interactive:off nicconfig where TcpipNetbiosOptions=0 call SetTcpipNetbios 2",
                        "wmic /interactive:off nicconfig where TcpipNetbiosOptions=1 call SetTcpipNetbios 2",
                    ],
                    "off": [],
                },
                "recommended": "on",
                "requires_admin": True,
                "risk": "moderate",
                "warning": "May break legacy file sharing and printer discovery on some networks.",
            },
            {
                "id": "disable_rdp_hardened",
                "name": "Disable RDP (Enhanced)",
                "description": "Deny RDP connections + encrypt RPC traffic + deny Remote Assistance",
                "registry": [
                    {
                        "path": r"HKLM\SYSTEM\CurrentControlSet\Control\Terminal Server",
                        "name": "fDenyTSConnections",
                        "type": "REG_DWORD",
                        "value_on": 1,
                        "value_off": 0,
                    },
                    {
                        "path": r"HKLM\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services",
                        "name": "fEncryptRPCTraffic",
                        "type": "REG_DWORD",
                        "value_on": 1,
                        "value_off": 0,
                    },
                    {
                        "path": r"HKLM\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services",
                        "name": "fAllowToGetHelp",
                        "type": "REG_DWORD",
                        "value_on": 0,
                        "value_off": 1,
                    },
                ],
                "recommended": "on",
                "requires_admin": True,
                "risk": "moderate",
                "warning": "Completely disables Remote Desktop and Remote Assistance.",
            },
            {
                "id": "hardened_tls_cipher_suites",
                "name": "Harden TLS Cipher Suites",
                "description": "Disable SSL 2.0/3.0, PCT, weak ciphers; enforce strong TLS cipher ordering",
                "registry": [
                    # Disable weak protocols
                    {"path": r"HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 2.0\Client", "name": "Enabled", "type": "REG_DWORD", "value_on": 0, "value_off": 1},
                    {"path": r"HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 2.0\Client", "name": "DisabledByDefault", "type": "REG_DWORD", "value_on": 1, "value_off": 0},
                    {"path": r"HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 2.0\Server", "name": "Enabled", "type": "REG_DWORD", "value_on": 0, "value_off": 1},
                    {"path": r"HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 2.0\Server", "name": "DisabledByDefault", "type": "REG_DWORD", "value_on": 1, "value_off": 0},
                    {"path": r"HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 3.0\Client", "name": "Enabled", "type": "REG_DWORD", "value_on": 0, "value_off": 1},
                    {"path": r"HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 3.0\Client", "name": "DisabledByDefault", "type": "REG_DWORD", "value_on": 1, "value_off": 0},
                    {"path": r"HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 3.0\Server", "name": "Enabled", "type": "REG_DWORD", "value_on": 0, "value_off": 1},
                    {"path": r"HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 3.0\Server", "name": "DisabledByDefault", "type": "REG_DWORD", "value_on": 1, "value_off": 0},
                    {"path": r"HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\PCT 1.0\Client", "name": "Enabled", "type": "REG_DWORD", "value_on": 0, "value_off": 1},
                    {"path": r"HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\PCT 1.0\Client", "name": "DisabledByDefault", "type": "REG_DWORD", "value_on": 1, "value_off": 0},
                    {"path": r"HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\PCT 1.0\Server", "name": "Enabled", "type": "REG_DWORD", "value_on": 0, "value_off": 1},
                    {"path": r"HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\PCT 1.0\Server", "name": "DisabledByDefault", "type": "REG_DWORD", "value_on": 1, "value_off": 0},
                    # Disable weak ciphers
                    {"path": r"HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\DES 56/56", "name": "Enabled", "type": "REG_DWORD", "value_on": 0, "value_off": 1},
                    {"path": r"HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\NULL", "name": "Enabled", "type": "REG_DWORD", "value_on": 0, "value_off": 1},
                    {"path": r"HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\RC2 128/128", "name": "Enabled", "type": "REG_DWORD", "value_on": 0, "value_off": 1},
                    {"path": r"HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\RC2 40/128", "name": "Enabled", "type": "REG_DWORD", "value_on": 0, "value_off": 1},
                    {"path": r"HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\RC2 56/128", "name": "Enabled", "type": "REG_DWORD", "value_on": 0, "value_off": 1},
                    {"path": r"HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\RC4 128/128", "name": "Enabled", "type": "REG_DWORD", "value_on": 0, "value_off": 1},
                    {"path": r"HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\RC4 40/128", "name": "Enabled", "type": "REG_DWORD", "value_on": 0, "value_off": 1},
                    {"path": r"HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\RC4 56/128", "name": "Enabled", "type": "REG_DWORD", "value_on": 0, "value_off": 1},
                    {"path": r"HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\RC4 64/128", "name": "Enabled", "type": "REG_DWORD", "value_on": 0, "value_off": 1},
                    {"path": r"HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\Triple DES 168", "name": "Enabled", "type": "REG_DWORD", "value_on": 0, "value_off": 1},
                    # Enable strong ciphers
                    {"path": r"HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\AES 128/128", "name": "Enabled", "type": "REG_DWORD", "value_on": 0xFFFFFFFF, "value_off": 0xFFFFFFFF},
                    {"path": r"HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\AES 256/256", "name": "Enabled", "type": "REG_DWORD", "value_on": 0xFFFFFFFF, "value_off": 0xFFFFFFFF},
                    # Enable strong hashes
                    {"path": r"HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Hashes\MD5", "name": "Enabled", "type": "REG_DWORD", "value_on": 0xFFFFFFFF, "value_off": 0xFFFFFFFF},
                    {"path": r"HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Hashes\SHA", "name": "Enabled", "type": "REG_DWORD", "value_on": 0xFFFFFFFF, "value_off": 0xFFFFFFFF},
                    {"path": r"HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Hashes\SHA256", "name": "Enabled", "type": "REG_DWORD", "value_on": 0xFFFFFFFF, "value_off": 0xFFFFFFFF},
                    {"path": r"HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Hashes\SHA384", "name": "Enabled", "type": "REG_DWORD", "value_on": 0xFFFFFFFF, "value_off": 0xFFFFFFFF},
                    {"path": r"HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Hashes\SHA512", "name": "Enabled", "type": "REG_DWORD", "value_on": 0xFFFFFFFF, "value_off": 0xFFFFFFFF},
                    # Enable strong key exchanges
                    {"path": r"HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\KeyExchangeAlgorithms\Diffie-Hellman", "name": "Enabled", "type": "REG_DWORD", "value_on": 0xFFFFFFFF, "value_off": 0xFFFFFFFF},
                    {"path": r"HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\KeyExchangeAlgorithms\ECDH", "name": "Enabled", "type": "REG_DWORD", "value_on": 0xFFFFFFFF, "value_off": 0xFFFFFFFF},
                    {"path": r"HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\KeyExchangeAlgorithms\PKCS", "name": "Enabled", "type": "REG_DWORD", "value_on": 0xFFFFFFFF, "value_off": 0xFFFFFFFF},
                    # TLS 1.2+ enabled by default
                    {"path": r"HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2\Client", "name": "Enabled", "type": "REG_DWORD", "value_on": 0xFFFFFFFF, "value_off": 0xFFFFFFFF},
                    {"path": r"HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2\Client", "name": "DisabledByDefault", "type": "REG_DWORD", "value_on": 0, "value_off": 1},
                    {"path": r"HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2\Server", "name": "Enabled", "type": "REG_DWORD", "value_on": 0xFFFFFFFF, "value_off": 0xFFFFFFFF},
                    {"path": r"HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2\Server", "name": "DisabledByDefault", "type": "REG_DWORD", "value_on": 0, "value_off": 1},
                ],
                "recommended": "on",
                "requires_admin": True,
                "risk": "moderate",
                "warning": "Some legacy applications or old IT equipment may fail to connect.",
            },
            {
                "id": "force_strong_crypto_net",
                "name": "Force Strong .NET Crypto",
                "description": "Enable SchUseStrongCrypto and SystemDefaultTlsVersions for .NET 2.0 and 4.0",
                "registry": [
                    {"path": r"HKLM\SOFTWARE\Wow6432Node\Microsoft\.NETFramework\v2.0.50727", "name": "SchUseStrongCrypto", "type": "REG_DWORD", "value_on": 1, "value_off": 0},
                    {"path": r"HKLM\SOFTWARE\Wow6432Node\Microsoft\.NETFramework\v2.0.50727", "name": "SystemDefaultTlsVersions", "type": "REG_DWORD", "value_on": 1, "value_off": 0},
                    {"path": r"HKLM\SOFTWARE\Microsoft\.NETFramework\v2.0.50727", "name": "SchUseStrongCrypto", "type": "REG_DWORD", "value_on": 1, "value_off": 0},
                    {"path": r"HKLM\SOFTWARE\Microsoft\.NETFramework\v2.0.50727", "name": "SystemDefaultTlsVersions", "type": "REG_DWORD", "value_on": 1, "value_off": 0},
                    {"path": r"HKLM\SOFTWARE\Microsoft\.NETFramework\v4.0.30319", "name": "SchUseStrongCrypto", "type": "REG_DWORD", "value_on": 1, "value_off": 0},
                    {"path": r"HKLM\SOFTWARE\Microsoft\.NETFramework\v4.0.30319", "name": "SystemDefaultTlsVersions", "type": "REG_DWORD", "value_on": 1, "value_off": 0},
                ],
                "recommended": "on",
                "requires_admin": True,
                "risk": "moderate",
                "warning": "Some very old .NET applications may fail to connect.",
            },
            {
                "id": "disable_wifi_sense",
                "name": "Disable Wi-Fi Sense",
                "description": "Prevent Windows from sharing Wi-Fi passwords with contacts",
                "registry": [
                    {"path": r"HKLM\SOFTWARE\Microsoft\WcmSvc\wifinetworkmanager\config", "name": "AutoConnectAllowedOEM", "type": "REG_DWORD", "value_on": 0, "value_off": 1},
                ],
                "recommended": "on",
                "requires_admin": True,
                "risk": "moderate",
                "warning": "Disables automatic Wi-Fi sharing with contacts.",
            },
            {
                "id": "force_fsutil_8dot3",
                "name": "Disable 8.3 Short Names",
                "description": "Disable 8.3 name generation on NTFS (reduces attack surface)",
                "commands": {
                    "on": ["fsutil behavior set disable8dot3 1"],
                    "off": ["fsutil behavior set disable8dot3 2"],
                },
                "recommended": "on",
                "requires_admin": True,
                "risk": "moderate",
                "warning": "Very old 16-bit applications may break without 8.3 short names.",
            },
            {
                "id": "force_fsutil_lastaccess",
                "name": "Enable Last Access Timestamps",
                "description": "Re-enable last access time tracking (fsutil behavior set disablelastaccess 0)",
                "commands": {
                    "on": ["fsutil behavior set disablelastaccess 0"],
                    "off": ["fsutil behavior set disablelastaccess 1"],
                },
                "recommended": "off",
                "requires_admin": True,
                "risk": "moderate",
                "warning": "Slight performance cost on HDDs; useful for forensic auditing.",
            },
            # ── RISKY ─────────────────────────────────────────────────
            {
                "id": "disable_com_dcom",
                "name": "Disable DCOM",
                "description": "Disable Distributed COM (EnableDCOM = N)",
                "registry": [
                    {"path": r"HKLM\Software\Microsoft\OLE", "name": "EnableDCOM", "type": "REG_SZ", "value_on": "N", "value_off": "Y"},
                ],
                "recommended": "off",
                "requires_admin": True,
                "risk": "risky",
                "warning": "Can break COM-based applications and some installers. Only use on standalone PCs.",
            },
            {
                "id": "disable_script_host",
                "name": "Disable Windows Script Host",
                "description": "Prevent .vbs and .js files from executing via WSH",
                "registry": [
                    {"path": r"HKCU\SOFTWARE\Microsoft\Windows Script Host\Settings", "name": "Enabled", "type": "REG_DWORD", "value_on": 0, "value_off": 1},
                ],
                "recommended": "off",
                "requires_admin": False,
                "risk": "risky",
                "warning": "Breaks .vbs and .js scripts entirely. Some enterprise tools depend on WSH.",
            },
            {
                "id": "disable_printer_drivers",
                "name": "Prevent Printer Driver Installation",
                "description": "Block users from installing printer drivers (AddPrinterDrivers = 1)",
                "registry": [
                    {"path": r"HKLM\SYSTEM\CurrentControlSet\Control\Print\Providers\LanMan Print Services\Servers", "name": "AddPrinterDrivers", "type": "REG_DWORD", "value_on": 1, "value_off": 0},
                ],
                "recommended": "off",
                "requires_admin": True,
                "risk": "risky",
                "warning": "You won't be able to add new printers without reverting this.",
            },
            {
                "id": "force_msi_elevated_off",
                "name": "Disable AlwaysInstallElevated",
                "description": "Prevent MSI packages from installing with elevated privileges",
                "registry": [
                    {"path": r"HKLM\SOFTWARE\Policies\Microsoft\Windows\Installer", "name": "AlwaysInstallElevated", "type": "REG_DWORD", "value_on": 0, "value_off": 1},
                ],
                "recommended": "on",
                "requires_admin": True,
                "risk": "risky",
                "warning": "Some enterprise MSI installers may fail.",
            },
            {
                "id": "remove_bloatware",
                "name": "Remove Bloatware Apps",
                "description": "Remove ~30 pre-installed UWP apps (Xbox, Weather, Mail, Maps, etc.)",
                "commands": {
                    "on": [
                        "Get-AppxPackage *Microsoft.BingWeather* -AllUsers | Remove-AppxPackage -ErrorAction SilentlyContinue",
                        "Get-AppxPackage *Microsoft.GetHelp* -AllUsers | Remove-AppxPackage -ErrorAction SilentlyContinue",
                        "Get-AppxPackage *Microsoft.Getstarted* -AllUsers | Remove-AppxPackage -ErrorAction SilentlyContinue",
                        "Get-AppxPackage *Microsoft.Messaging* -AllUsers | Remove-AppxPackage -ErrorAction SilentlyContinue",
                        "Get-AppxPackage *Microsoft.Microsoft3DViewer* -AllUsers | Remove-AppxPackage -ErrorAction SilentlyContinue",
                        "Get-AppxPackage *Microsoft.MicrosoftOfficeHub* -AllUsers | Remove-AppxPackage -ErrorAction SilentlyContinue",
                        "Get-AppxPackage *Microsoft.MicrosoftSolitaireCollection* -AllUsers | Remove-AppxPackage -ErrorAction SilentlyContinue",
                        "Get-AppxPackage *Microsoft.MixedReality.Portal* -AllUsers | Remove-AppxPackage -ErrorAction SilentlyContinue",
                        "Get-AppxPackage *Microsoft.OneConnect* -AllUsers | Remove-AppxPackage -ErrorAction SilentlyContinue",
                        "Get-AppxPackage *Microsoft.Print3D* -AllUsers | Remove-AppxPackage -ErrorAction SilentlyContinue",
                        "Get-AppxPackage *Microsoft.Wallet* -AllUsers | Remove-AppxPackage -ErrorAction SilentlyContinue",
                        "Get-AppxPackage *Microsoft.WindowsFeedbackHub* -AllUsers | Remove-AppxPackage -ErrorAction SilentlyContinue",
                        "Get-AppxPackage *Microsoft.WindowsMaps* -AllUsers | Remove-AppxPackage -ErrorAction SilentlyContinue",
                        "Get-AppxPackage *Microsoft.WindowsSoundRecorder* -AllUsers | Remove-AppxPackage -ErrorAction SilentlyContinue",
                        "Get-AppxPackage *Microsoft.Xbox.TCUI* -AllUsers | Remove-AppxPackage -ErrorAction SilentlyContinue",
                        "Get-AppxPackage *Microsoft.XboxApp* -AllUsers | Remove-AppxPackage -ErrorAction SilentlyContinue",
                        "Get-AppxPackage *Microsoft.XboxGameOverlay* -AllUsers | Remove-AppxPackage -ErrorAction SilentlyContinue",
                        "Get-AppxPackage *Microsoft.XboxGamingOverlay* -AllUsers | Remove-AppxPackage -ErrorAction SilentlyContinue",
                        "Get-AppxPackage *Microsoft.XboxIdentityProvider* -AllUsers | Remove-AppxPackage -ErrorAction SilentlyContinue",
                        "Get-AppxPackage *Microsoft.YourPhone* -AllUsers | Remove-AppxPackage -ErrorAction SilentlyContinue",
                        "Get-AppxPackage *Microsoft.ZuneMusic* -AllUsers | Remove-AppxPackage -ErrorAction SilentlyContinue",
                        "Get-AppxPackage *Microsoft.ZuneVideo* -AllUsers | Remove-AppxPackage -ErrorAction SilentlyContinue",
                        "Get-AppxPackage *Microsoft.Advertising.Xaml* -AllUsers | Remove-AppxPackage -ErrorAction SilentlyContinue",
                        "Get-AppxPackage *Microsoft.Services.Store.Engagement* -AllUsers | Remove-AppxPackage -ErrorAction SilentlyContinue",
                    ],
                    "off": [],
                },
                "recommended": "off",
                "requires_admin": True,
                "risk": "risky",
                "warning": "Some apps may be wanted (Mail, Photos, Maps). Cannot easily undo — requires reinstallation from Store.",
            },
            {
                "id": "harden_office_macros",
                "name": "Harden Office Macro Settings",
                "description": "Disable DDE, set VBAWarnings=4, PackagerPrompt=2 for Office 12-16",
                "registry": [
                    # Office 16 (2019/365)
                    {"path": r"HKCU\SOFTWARE\Microsoft\Office\16.0\Word\Security", "name": "PackagerPrompt", "type": "REG_DWORD", "value_on": 2, "value_off": 1},
                    {"path": r"HKCU\SOFTWARE\Microsoft\Office\16.0\Word\Security", "name": "VBAWarnings", "type": "REG_DWORD", "value_on": 4, "value_off": 2},
                    {"path": r"HKCU\SOFTWARE\Microsoft\Office\16.0\Word\Security", "name": "AllowDDE", "type": "REG_DWORD", "value_on": 0, "value_off": 1},
                    {"path": r"HKCU\SOFTWARE\Microsoft\Office\16.0\Excel\Security", "name": "PackagerPrompt", "type": "REG_DWORD", "value_on": 2, "value_off": 1},
                    {"path": r"HKCU\SOFTWARE\Microsoft\Office\16.0\Excel\Security", "name": "VBAWarnings", "type": "REG_DWORD", "value_on": 4, "value_off": 2},
                    {"path": r"HKCU\SOFTWARE\Microsoft\Office\16.0\Excel\Security", "name": "WorkbookLinkWarnings", "type": "REG_DWORD", "value_on": 2, "value_off": 1},
                    {"path": r"HKCU\SOFTWARE\Microsoft\Office\16.0\Excel\Options", "name": "DontUpdateLinks", "type": "REG_DWORD", "value_on": 1, "value_off": 0},
                    {"path": r"HKCU\SOFTWARE\Microsoft\Office\16.0\PowerPoint\Security", "name": "PackagerPrompt", "type": "REG_DWORD", "value_on": 2, "value_off": 1},
                    {"path": r"HKCU\SOFTWARE\Microsoft\Office\16.0\PowerPoint\Security", "name": "VBAWarnings", "type": "REG_DWORD", "value_on": 4, "value_off": 2},
                    {"path": r"HKCU\SOFTWARE\Microsoft\Office\Common\Security", "name": "DisableAllActiveX", "type": "REG_DWORD", "value_on": 1, "value_off": 0},
                ],
                "recommended": "off",
                "requires_admin": False,
                "risk": "risky",
                "warning": "Breaks some Office macro automation. VBAWarnings=4 blocks all macros without notification.",
            },
            {
                "id": "edge_hardening",
                "name": "Harden Microsoft Edge",
                "description": "Block background mode, enforce site isolation, prevent SmartScreen override, enforce TLS errors, force PUA protection, block history deletion",
                "registry": [
                    {"path": r"HKLM\Software\Policies\Microsoft\Edge", "name": "BackgroundModeEnabled", "type": "REG_DWORD", "value_on": 0, "value_off": 1},
                    {"path": r"HKLM\Software\Policies\Microsoft\Edge", "name": "SitePerProcess", "type": "REG_DWORD", "value_on": 1, "value_off": 0},
                    {"path": r"HKLM\Software\Policies\Microsoft\Edge", "name": "PreventSmartScreenPromptOverride", "type": "REG_DWORD", "value_on": 1, "value_off": 0},
                    {"path": r"HKLM\Software\Policies\Microsoft\Edge", "name": "PreventSmartScreenPromptOverrideForFiles", "type": "REG_DWORD", "value_on": 1, "value_off": 0},
                    {"path": r"HKLM\Software\Policies\Microsoft\Edge", "name": "SSLErrorOverrideAllowed", "type": "REG_DWORD", "value_on": 0, "value_off": 1},
                    {"path": r"HKLM\Software\Policies\Microsoft\Edge", "name": "SmartScreenPuaEnabled", "type": "REG_DWORD", "value_on": 1, "value_off": 0},
                    {"path": r"HKLM\Software\Policies\Microsoft\Edge", "name": "AllowDeletingBrowserHistory", "type": "REG_DWORD", "value_on": 0, "value_off": 1},
                ],
                "recommended": "off",
                "requires_admin": True,
                "risk": "risky",
                "warning": "Restricts some Edge features. History cannot be deleted. uBlock Origin is force-installed.",
            },
            {
                "id": "chrome_hardening",
                "name": "Harden Google Chrome",
                "description": "Force SafeBrowsing, disable telemetry, enforce security policies",
                "registry": [
                    {"path": r"HKLM\SOFTWARE\Policies\Google\Chrome", "name": "SitePerProcess", "type": "REG_DWORD", "value_on": 1, "value_off": 0},
                    {"path": r"HKLM\SOFTWARE\Policies\Google\Chrome", "name": "AudioSandboxEnabled", "type": "REG_DWORD", "value_on": 1, "value_off": 0},
                    {"path": r"HKLM\SOFTWARE\Policies\Google\Chrome", "name": "BackgroundModeEnabled", "type": "REG_DWORD", "value_on": 0, "value_off": 1},
                    {"path": r"HKLM\SOFTWARE\Policies\Google\Chrome", "name": "MetricsReportingEnabled", "type": "REG_DWORD", "value_on": 0, "value_off": 1},
                    {"path": r"HKLM\SOFTWARE\Policies\Google\Chrome", "name": "SearchSuggestEnabled", "type": "REG_DWORD", "value_on": 0, "value_off": 1},
                    {"path": r"HKLM\SOFTWARE\Policies\Google\Chrome", "name": "UrlKeyedAnonymizedDataCollectionEnabled", "type": "REG_DWORD", "value_on": 0, "value_off": 1},
                    {"path": r"HKLM\SOFTWARE\Policies\Google\Chrome", "name": "ChromeCleanupEnabled", "type": "REG_DWORD", "value_on": 0, "value_off": 1},
                    {"path": r"HKLM\SOFTWARE\Policies\Google\Chrome", "name": "ChromeCleanupReportingEnabled", "type": "REG_DWORD", "value_on": 0, "value_off": 1},
                    {"path": r"HKLM\SOFTWARE\Policies\Google\Chrome", "name": "EnableMediaRouter", "type": "REG_DWORD", "value_on": 0, "value_off": 1},
                    {"path": r"HKLM\SOFTWARE\Policies\Google\Chrome", "name": "BrowserGuestModeEnabled", "type": "REG_DWORD", "value_on": 0, "value_off": 1},
                ],
                "recommended": "off",
                "requires_admin": True,
                "risk": "risky",
                "warning": "Disables Chrome guest mode, background mode, and telemetry. Some features restricted.",
            },
            {
                "id": "disable_ipv6_protocol",
                "name": "Disable IPv6",
                "description": "Set DisabledComponents = 0xFF to fully disable IPv6",
                "registry": [
                    {"path": r"HKLM\SYSTEM\CurrentControlSet\services\tcpip6\parameters", "name": "DisabledComponents", "type": "REG_DWORD", "value_on": 255, "value_off": 0},
                ],
                "recommended": "off",
                "requires_admin": True,
                "risk": "risky",
                "warning": "⚠️ Can break networking on IPv6 networks. Only disable if you're sure you don't need IPv6.",
            },
            {
                "id": "disable_reserved_storage",
                "name": "Disable Reserved Storage",
                "description": "Disable Windows reserved storage (DISM)",
                "commands": {
                    "on": ["DISM /Online /Set-ReservedStorageState /State:Disabled"],
                    "off": ["DISM /Online /Set-ReservedStorageState /State:Enabled"],
                },
                "recommended": "off",
                "requires_admin": True,
                "script_only": True,
                "risk": "risky",
                "warning": "⚠️ Windows Update may fail without reserved storage. Only disable if disk space is critically low.",
            },
            {
                "id": "block_process_netconns",
                "name": "Block Process Network Connections",
                "description": "Firewall rules blocking certutil, wscript, cscript, mshta, rundll32, etc. from outbound connections",
                "commands": {
                    "on": [
                        'netsh advfirewall firewall add rule name="Block certutil.exe netconns" program="%systemroot%\\system32\\certutil.exe" protocol=tcp dir=out enable=yes action=block profile=any',
                        'netsh advfirewall firewall add rule name="Block wscript.exe netconns" program="%systemroot%\\system32\\wscript.exe" protocol=tcp dir=out enable=yes action=block profile=any',
                        'netsh advfirewall firewall add rule name="Block cscript.exe netconns" program="%systemroot%\\system32\\cscript.exe" protocol=tcp dir=out enable=yes action=block profile=any',
                        'netsh advfirewall firewall add rule name="Block mshta.exe netconns" program="%systemroot%\\system32\\mshta.exe" protocol=tcp dir=out enable=yes action=block profile=any',
                        'netsh advfirewall firewall add rule name="Block rundll32.exe netconns" program="%systemroot%\\system32\\rundll32.exe" protocol=tcp dir=out enable=yes action=block profile=any',
                        'netsh advfirewall firewall add rule name="Block msiexec.exe netconns" program="%systemroot%\\system32\\msiexec.exe" protocol=tcp dir=out enable=yes action=block profile=any',
                        'netsh advfirewall firewall add rule name="Block regsvr32.exe netconns" program="%systemroot%\\system32\\regsvr32.exe" protocol=tcp dir=out enable=yes action=block profile=any',
                    ],
                    "off": [
                        'netsh advfirewall firewall delete rule name="Block certutil.exe netconns"',
                        'netsh advfirewall firewall delete rule name="Block wscript.exe netconns"',
                        'netsh advfirewall firewall delete rule name="Block cscript.exe netconns"',
                        'netsh advfirewall firewall delete rule name="Block mshta.exe netconns"',
                        'netsh advfirewall firewall delete rule name="Block rundll32.exe netconns"',
                        'netsh advfirewall firewall delete rule name="Block msiexec.exe netconns"',
                        'netsh advfirewall firewall delete rule name="Block regsvr32.exe netconns"',
                    ],
                },
                "recommended": "on",
                "requires_admin": True,
                "risk": "risky",
                "warning": "Some legitimate tools use these processes for network access. May break specific software.",
            },
            {
                "id": "force_windows_defender_pua",
                "name": "Enable PUA Protection",
                "description": "Set Defender PUAProtection to block potentially unwanted applications",
                "commands": {
                    "on": ["Set-MpPreference -PUAProtection enable -ErrorAction SilentlyContinue"],
                    "off": ["Set-MpPreference -PUAProtection disable -ErrorAction SilentlyContinue"],
                },
                "recommended": "off",
                "requires_admin": True,
                "risk": "risky",
                "warning": "May flag legitimate software as potentially unwanted.",
            },
            {
                "id": "adobe_reader_hardening",
                "name": "Harden Adobe Reader",
                "description": "Disable Flash, JavaScript, enhanced security, PDF handler switching in Adobe Reader",
                "registry": [
                    {"path": r"HKLM\Software\Policies\Adobe\Acrobat Reader\DC\FeatureLockDown", "name": "bEnableFlash", "type": "REG_DWORD", "value_on": 0, "value_off": 1},
                    {"path": r"HKLM\Software\Policies\Adobe\Acrobat Reader\DC\FeatureLockDown", "name": "bEnhancedSecurityInBrowser", "type": "REG_DWORD", "value_on": 1, "value_off": 0},
                    {"path": r"HKLM\Software\Policies\Adobe\Acrobat Reader\DC\FeatureLockDown", "name": "bEnhancedSecurityStandalone", "type": "REG_DWORD", "value_on": 1, "value_off": 0},
                    {"path": r"HKLM\Software\Policies\Adobe\Acrobat Reader\DC\FeatureLockDown", "name": "bProtectedMode", "type": "REG_DWORD", "value_on": 1, "value_off": 0},
                    {"path": r"HKLM\Software\Policies\Adobe\Acrobat Reader\DC\FeatureLockDown", "name": "bDisablePDFHandlerSwitching", "type": "REG_DWORD", "value_on": 1, "value_off": 0},
                    {"path": r"HKLM\Software\Policies\Adobe\Acrobat Reader\DC\FeatureLockDown", "name": "iFileAttachmentPerms", "type": "REG_DWORD", "value_on": 1, "value_off": 0},
                    {"path": r"HKLM\Software\Policies\Adobe\Acrobat Reader\DC\FeatureLockDown", "name": "iProtectedView", "type": "REG_DWORD", "value_on": 2, "value_off": 0},
                ],
                "recommended": "off",
                "requires_admin": True,
                "risk": "risky",
                "warning": "Only applies if Adobe Reader is installed. Restricts some Reader features.",
            },
        ],
    },
}


def get_all_tweaks():
    """Return a flat list of all tweaks with their category."""
    result = []
    for cat_name, cat_data in TWEAK_CATEGORIES.items():
        for tweak in cat_data["tweaks"]:
            result.append({**tweak, "category": cat_name, "category_icon": cat_data["icon"]})
    return result


def get_tweak_by_id(tweak_id):
    """Find a tweak by its ID."""
    for cat_name, cat_data in TWEAK_CATEGORIES.items():
        for tweak in cat_data["tweaks"]:
            if tweak["id"] == tweak_id:
                return {**tweak, "category": cat_name}
    return None